= Hawkular-Metrics 0.2.7 release
Heiko W. Rupp
2015-02-16
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, metrics, release
:idprefix:

Hawkular-metrics has published under its old name _rhq-metrics_ its version 0.2.7 release.
From Stefans announcement:

I want to summarize the latest release of the RHQ Metrics project and the future of the project.


== RHQ Metrics migrates to Hawkular organization

Release 0.2.7 of the RHQ Metrics is the last one from the current repository. But do not panic! Beyond the mechanics of the transfer and rename, the development will continue with the regular crew.

For the migration, two project repositories (rhq-metrics and rhq-metrics-openshift) will just be transferred to the Hawkular organization. The code from rhqm-charts was already moved to Hawkular, so we will just close the RHQ repository. We will have a follow up communication once all the infrastructure is in place under the new organization.


== RHQ Metrics 0.2.7 was released today

This release has mainly stability fixes and minor enhancements. The Keycloak integration was delayed and not part of this release (as announced in the planning notes). For more details checkout the Github release notes.

Github Release:
https://github.com/rhq-project/rhq-metrics/releases/tag/0.2.7

JBoss Nexus Maven artifacts:
http://origin-repository.jboss.org/nexus/content/repositories/public/org/rhq/metrics/


== OpenShift Cartridge for RHQ Metrics 0.2.7

The cartridge supports RHQ Metrics 0.2.7, 0.2.6, and 0.2.5. Just a reminder, the cartridge is the simplest and easiest way to get a public facing instance of RHQ Metrics in just a few minutes with a single command. The cartridge configures Cassandra, Wildfly, and RHQ Metrics (REST interface and UI console) to run in a single gear. For more details please visit the Github repository of the project.

Sample command to create a new RHQ Metrics deployment:
rhc app create test_app https://raw.githubusercontent.com/rhq-project/rhq-metrics-openshift/master/metadata/manifest.yml

Github Repository:
https://github.com/rhq-project/rhq-metrics-openshift


A big "Thank you!" goes to John Sanda, Mike Thompson, Heiko Rupp, and Thomas Segismont for their project contributions.


Any discussion, suggestions or contributions are more than welcomed; so feel free to reply to this email or comment directly on the various forum threads.


Thank you,
Stefan Negrea