= Dockerized Hawkular builds available
Heiko W. Rupp
2015-03-30
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, kettle, docker
:idprefix:

As described earlier, we have assembled all the components of Hawkular into a single package, the _Kettle_.
This allows you to just build/download one package, start and work with it instead of caring of the individual
sub-packages.

To make the process to play with Hawkular even easier, we have also created a build-pipeline that creates a Docker
image out of the Kettle and publishes it to Docker Hub as hawkular/hawkular.

You can download and run them like this:

[source,shell]
----
$ docker run -d -p 8081:8080 hawkular/hawkular
----

After the download of the image has finished, it will take a while until Hawkular is fully started up.
When it is up, you can reach the Hawkular UI at http://localhost:8081/  ( If you are
running docker on OS/X via boot2docker, you need to use the IP address that is stored in the `DOCKER_HOST`
environment variable instead of `localhost`.)

More information is available in the
link:/docs/user/getting-started[Getting started] document.
