= Hawkular Services 0.30.0.Final
Heiko W. Rupp
2017-01-31
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, release, hawkular-services

Hawkular services is a ready to run distribution of Hawkular-Metrics with Alerts, Inventory, the WildFly agent and other components.
The version https://repository.jboss.org/nexus/content/groups/public/org/hawkular/services/hawkular-services-dist/0.30.0.Final/hawkular-services-dist-0.30.0.Final.zip[0.30.0.Final] has just been released and is ready to be tested and integrated with other projects.


== What's in this release


This release includes those changes:

* The WildFly agent now supports EAP 6(.4). See Subtasks of https://issues.jboss.org/browse/HAWKULAR-1175[HAWKULAR-1175]
* An Event is forwarded to subscribed clients (like ManageIQ). See https://issues.jboss.org/browse/HAWKULAR-1188[HAWKULAR-1188]
* Number of threads created by ActiveMQ are now limited to 30 to prevent start issues by running into file descriptor limits.


Hawkular Services is released every week on Tuesdays.

== Get started
To get started with Hawkular Services, https://repository.jboss.org/nexus/content/groups/public/org/hawkular/services/hawkular-services-dist/0.30.0.Final/hawkular-services-dist-0.30.0.Final.zip[download the latest release], unzip it,
add a user and set the Agent to use the credentials for the user just added.

It can be accomplished with the following commands:

[source,bash]
----
export HAWKULAR_HOME="/path/to/hawkular-services"
export HAWKULAR_USERNAME="jdoe"
export HAWKULAR_PASSWORD="password"

cd "${HAWKULAR_HOME}"
"${HAWKULAR_HOME}/bin/add-user.sh" \
  -a \
  -u "${HAWKULAR_USERNAME}" \
  -p "${HAWKULAR_PASSWORD}" \
  -g read-write,read-only
"${HAWKULAR_HOME}/bin/standalone.sh" -Dhawkular.rest.user="${HAWKULAR_USERNAME}" -Dhawkular.rest.password="${HAWKULAR_PASSWORD}"
----

Before starting the server, you need to have Cassandra 3.0.9 up and running with the RPC port enabled either via
setting the env variable of `CASSANDRA_START_RPC` to `true`

or by editing `cassandra.yml` and setting it there:

[source,yml]
----
# Whether to start the thrift rpc server.
start_rpc: true
----

Using `ccm` you can use this to update the config: `ccm updateconf 'start_rpc: true'`.
Another option is via `nodetool enablethrift`.

=== Using Postgres

To use Postgres as backend you need to pass additional properties to the `standalone.sh` command
above:

[source, bash]
----
"${HAWKULAR_HOME}/bin/standalone.sh" -Dhawkular.rest.user="${HAWKULAR_USERNAME}" \
    -Dhawkular.rest.password="${HAWKULAR_PASSWORD} \
    -Dhawkular.inventory.sql.jdbc.url=jdbc:postgresql://1.2.3.4:5432/hawkular \
    -Dhawkular.inventory.sql.jdbc.username=jdoe \
    -Dhawkular.inventory.sql.jdbc.password=password
----

To use a postgres database called _hawkular_ on host _1.2.3.4_ owned by a user _jdoe_ with a
 password of _password_.

See also
http://www.hawkular.org/hawkular-services/docs/user-guide/inventory/index.html#configuration-properties.


=== Build from master and Cassandra

If you build from master, you can pass `-Pembeddedc` to get a distribution with embedded Cassandra for local development.
Similarly if you build via `-Pdev` a default user of _jdoe/password_ will be installed and also be used with the agent.

== Use Grafana with Hawkular-services

We do now have a Grafana datasource to make it easier to connect to Hawkular-services from Grafana.
You can download it from https://grafana.net/plugins/hawkular-datasource[Grafana.net].
The https://github.com/hawkular/hawkular-grafana-datasource[website of the datasource tells more].

== Get started via (inofficial) Docker builds

There are inofficial Docker images of the release and also an instrumented WildFly available on
DockerHub at https://hub.docker.com/r/pilhuhn/hawkular-services/[Hawkular services]
and https://hub.docker.com/r/pilhuhn/hawkfly/[Instrumented WildFly].

Both images have been instrumented with the _jdoe/password_ user for the Hawkular server and the agent.

See also http://pilhuhn.blogspot.de/2016/06/using-hawkular-services-via-docker.html on some more
details about using those images.