= Terms
Heiko Rupp
2015-03-30
:description: Hawkular terms
:icons: font
:jbake-type: page
:jbake-status: published
:toc: macro
:toc-title:

Hawkular sometimes uses terms that are not everyone is familiar with. This page is an effort to clarify those.

== General terms

Dampening:: This is a concept in Hawkular-Alerts that allows to "verify" an alerting condition. As an example,
 sometimes one only wants to trigger an alert when the same conditions occurs at least three times in 5 minutes.

Feed:: A feed is a source of incoming data to pe processed by Hawkular. Usually a feed is something like an agent
 that is collecting data, but it could also be an application sending data or a shell-script using the `curl` command
 to submit the data.

Member:: an User or Organization that can be part of an Organization.

Organization:: a non-user which has an Owner and a set of Members. In most cases, consumers of Hawkular Accounts
 do not need to deal directly with organizations.

Owner:: owns a Resource footnoteref:[resource,A Resource following the definition of Hawkular Accounts], and can be
(currently) either a Hawkular User or an Organization.

Persona:: either a User or an Organization. A real User can be impersonating an Organization, so, this Organization
 would be the current Persona. In most cases, the current Persona corresponds to an intuitive notion of the
 "current user" or "current tenant".

Tenant:: implemented in Hawkular with the concept of Persona. Each tenant has an isolated view of the system and
 does not have access to data outside of its own boundaries.

Pinger:: A component that "pings" footnoteref:[ping, Not an ICMP-Ping, but a http call.] remote http servers and
reports
back
 the server status along with the time it took.

Trigger-Definition:: The Trigger definition consits of the rules when incoming conditions should trigger (fire) an
 alert.

User:: a real user of the application. In most cases, consumers of Hawkular Accounts do not need to deal directly
 with users.

== Hawkular Accounts

When dealing with Hawkular Accounts, some terms might differ from the other Hawkular components. The following is a
list of definitions for the terms used on Accounts' context which might have different meanings on other components:

Resource:: something that you want to protect; it might be an Alert, an Inventory item, a Metric, ...

And the following are a list of other common terms in the realm of authentication and authorization:

Operation:: an action that a Persona performs on a resource, such as "metrics-create"

Role:: the role that a Persona has on a given organization, such as "Super User".

Permission:: a relationship between a Role and an Operation, such as "Super User can execute metrics-create"

