= Getting Started
Heiko Rupp
2015-02-25
:description: How to get started with Hawkular
:jbake-type: page
:jbake-status: published
:icons: font
:toc: macro
:toc-title:

toc::[]

== Getting Started with Hawkular.

NOTE
Right now there is no Hawkular distribution to download and go. We are working on it.

Once we have a distribution available, you can unzip and start the server

[source,shell]
----
unzip hawkular.zip
cd hawkular
cd wildfly-8.2.0.Final
bin/standalone.sh  # use standalone.bat on Windows
----

You can then navigate your browser to http://localhost:8080/

=== Try via Docker

Hawkular is publishing builds to https://registry.hub.docker.com/u/hawkular/hawkular/[Docker Hub] that you can try
and download from Docker.

NOTE: Those builds are not secured and should not be run on a public network.

The following assumes that you have Docker installed and started if necessary.

[source, shell]
----
$ docker run -d -p 8081:8080 hawkular/hawkular   #<1>
Unable to find image 'hawkular/hawkular:latest' locally #<2>
Pulling repository hawkular/hawkular
26830c504ec5: Download complete
[...]
612ba72033af: Download complete
Status: Downloaded newer image for hawkular/hawkular:latest #<3>
c792a1f059521f6ae99  #<4>
----
<1> Start the docker container in the background (`-d`) and tell it that the internal port 8080 should be
available as port 8081 (`-p 8081:8080).
<2> This is the first time that image is to be used, so docker is downloading it from Docker Hub, which may take a
while. Starting the same image the next time will only take a few seconds.
<3> Download has finished, Hawkular server will be started
<4> Hawkular server has started with a container id of `c792a1f0595`. This id will be different for each start.

Now as Docker is running the container and you can reach the Hawkular UI at http://localhost:8081/  ( If you are
running docker on OS/X via boot2docker, you need to use the IP address that is stored in the `DOCKER_HOST`
environment variable instead of `localhost`.)

When you are done, you can shut down the container via

[source,shell]
----
$ docker stop c792a1f0595  #<1>
----
<1> Container id that was emitted above

To upgrade to a newer build just run

[source,shell]
----
$ docker pull hawkular/hawkular:latest  #<1>
Pulling repository hawkular/hawkular
26830c504ec5: Download complete
511136ea3c5a: Download complete
[...]
612ba72033af: Download complete
Status: Image is up to date for hawkular/hawkular:latest #<2>
----
<1> We ask for the latest build
<2> In this case the local one was already the latest, so we are good here.

=== Working on Hawkular source

If you are interested in hacking on Hawkular, or building it from source, then check out
link:/docs/dev/development.html[Development resources]

== Install a Wildfly monitoring agent

If you wish to monitor a WildFly instance,  you can do so with the following steps:

. Download the WildFly module from http://download.jboss.org/hawkular/wildfly-monitor/0.0.2/hawkular-monitor-0.0.2-module.zip[here].
. Unzip the file inside the `modules` directory of  your WildFly 8.2 instance
. Add the following subsystem declaration in the `standalone/configuration/standalone.xml` file of your WildFly instance, the `url` of the storage adapter should be the URL of your Hawkular server.

[source,xml]
----
 <subsystem enabled="true" apiJndiName="java:global/hawkular/agent/monitor/api" numMetricSchedulerThreads="3" numAvailSchedulerThreads="3" xmlns="urn:org.hawkular.agent.monitor:monitor:1.0">
            <storage-adapter type="HAWKULAR" url="http://localhost:8080" context="/hawkular-bus/message/" restContext="/hawkular-metrics/"/>
            <diagnostics enabled="true" reportTo="LOG" interval="5" timeUnits="minutes"/>
            <metric-set-dmr name="platform" enabled="true">
                <metric-dmr name="heap.used" interval="30" timeUnits="seconds" resource="/core-service=platform-mbean/type=memory" attribute="heap-memory-usage#used"/>
                <metric-dmr name="heap.committed" interval="1" timeUnits="minutes" resource="/core-service=platform-mbean/type=memory" attribute="heap-memory-usage#committed"/>
                <metric-dmr name="non-heap.used" interval="30" timeUnits="seconds" resource="/core-service=platform-mbean/type=memory" attribute="non-heap-memory-usage#used"/>
                <metric-dmr name="non-heap.committed" interval="1" timeUnits="minutes" resource="/core-service=platform-mbean/type=memory" attribute="non-heap-memory-usage#committed"/>
                <metric-dmr name="thread-count" interval="2" timeUnits="minutes" resource="/core-service=platform-mbean/type=threading" attribute="thread-count"/>
            </metric-set-dmr>
            <avail-set-dmr name="server-availabilities" enabled="true">
                <avail-dmr name="app-server" interval="30" timeUnits="seconds" resource="/" attribute="server-state" upRegex="run.*"/>
                <avail-dmr name="hawkular-bus-broker" interval="1" timeUnits="minutes" resource="/subsystem=hawkular-bus-broker"/>
            </avail-set-dmr>
            <managed-servers>
                <local-dmr enabled="true" metricSets="platform" availSets="server-availabilities"/>
            </managed-servers>
        </subsystem>
----

WARNING: It is known that this only works with WildFly 8.2 at the moment and not with WildFly 9.
