= Quick start
Heiko Rupp
2015-06-08
:description: Fastest route to get Hawkular up and running
:jbake-type: page
:jbake-status: published
:icons: font
:toc: macro
:toc-title:

toc::[]

== Before we start
We'll install an Hawkular server and then instrument a WildFly server to be manageable by the server.
We suppose that you have Java 8 already installed on your machine.
To install the server we propose an alternative using Docker, we suppose that you have Docker already installed.

Hawkular uses Cassandra. Out of the box Hawkular is configured to use an embedded
single-node cluster. You do not have to worry about setting up and configuring
Cassandra before getting started with Hawkular.

Hawkular uses Keycloak. Out of the box Hawkular is configured to use an embedded Keycloak server for user management.
It's pre-configured and ready to use, but make sure to use an external Keycloak server on more serious environments.

For a more proper installation, please refer to link:user/installation-guide.html[the installation guide]

NOTE: The embedded Cassandra is not intended for production use, we definitely recommend to use a separate Cassandra server.

== Step 1: Installing Hawkular server
=== Option A: Install from a zip file on any operating system
Download
http://download.jboss.org/hawkular/hawkular/{hawkular_released_version}/hawkular-dist-{hawkular_released_version}.zip[Hawkular {hawkular_released_version} (zip)]
and then unzip and start the server as shown below.

.Unzip and start the server
[source,shell,subs="+attributes"]
----
unzip hawkular-dist-{hawkular_released_version}.zip
cd hawkular-{hawkular_released_version}
bin/standalone.sh  # use standalone.bat on Windows
----

You can then navigate your browser to http://localhost:8080/. When you see the login screen,
you have to register as a user and will then be redirected to the main Hawkular page.

Should you decide to use another hostname and/or port, you'd need to change the system property `keycloak.server.url`
 either via command line or by changing the `standalone.xml`. Example:

[source,bash]
----
bin/standalone.sh -Dkeycloak.server.url=http://localhost:8180/auth
----

For a more permanent solution, you can change the `standalone.xml` by setting an appropriate value for the system
property:
[source,xml]
----
<property name="keycloak.server.url" value="http://localhost:8180/auth"/>
----

Then, just start Keycloak as usual:
[source,bash]
----
bin/standalone.sh
----

=== Option B: Install from a docker image

Hawkular is publishing builds to https://registry.hub.docker.com/u/jboss/hawkular-aio/[Docker Hub] that you can try
and download from Docker.

NOTE: Those builds are not secured and should not be run on a public network.

The following assumes that you have Docker installed and started if necessary.

[source, shell]
----
$ docker run -d -p 8080:8080 jboss/hawkular-aio   #<1>
Unable to find image 'jboss/hawkular-aio:latest' locally #<2>
latest: Pulling from docker.io/jboss/hawkular-aio
26830c504ec5: Download complete
[...]
612ba72033af: Download complete
Digest: sha256:dd0db25c80464f93fb652906317c003d29bf19e9ba6622ddf4df9377c56d3823
Status: Downloaded newer image for jboss/hawkular-aio:latest #<3>
c792a1f059521f6ae99  #<4>
----
<1> Start the docker container in the background (`-d`) and tell it that the internal (container's) port 8080 should be
available as host port 8080 (`-p 8080:8080).
<2> This is the first time that image is to be used, so docker is downloading it from Docker Hub, which may take a
while. Starting the same image the next time will only take a few seconds.
<3> Download has finished, Hawkular server will be started
<4> Hawkular server has started with a container id of `c792a1f0595`. This id will be different for each start.

Now as Docker is running the container and you can reach the Hawkular UI at http://localhost:8080/

NOTE: If you are running docker on OS/X via boot2docker, you need to use the IP address that is stored in the `DOCKER_HOST`
environment variable instead of `localhost`.)

[NOTE]
.Stopping the Docker container
=======================
When you are done, you can shut down the container via:

[source,shell]
----
$ docker stop c792a1f0595  #<1>
----
<1> Container id that was emitted above
=======================

Later if you want to upgrade to a newer build just run:

[source,shell]
----
$ docker pull jboss/hawkular-aio:latest  #<1>
Pulling repository jboss/hawkular-aio
26830c504ec5: Download complete
511136ea3c5a: Download complete
[...]
612ba72033af: Download complete
Status: Image is up to date for jboss/hawkular-aio:latest #<2>
----
<1> We ask for the latest build
<2> In this case the local one was already the latest, so we are good here.

You can then navigate your browser to http://localhost:8080/. When you see the login screen, you have to register as a user and will then be redirected to the main Hawkular page.

== Step 2: Install a Hawkular WildFly Agent

Now that the server is installed and you have a user registered you would likely want to push some data into that server, at this stage, the only agent we provide is an agent for WildFly 9 and above.

Here are the steps to install the Hawkular WildFly agent into your own WildFly Server installation:

* Download the Hawkular WildFly Agent installer
You can download the installer from http://localhost:8080/hawkular/wildfly-agent/installer[your Hawkular Server that is already running].
* Run the installer, telling it the location of your WildFly Server.

----
java -jar hawkular-wildfly-agent-installer*.jar --target-location=/your/wildfly/server
----

TIP: If you plan on monitoring multiple servers, pass in the command line option "--managed-server-name=YourUniqueName" where "YourUniqueName" is some *unique* value among your managed machines. (Alpha8 note: this option is not available in Alpha8. To set this if you are running Alpha8, you need to change the "name" attribute in the "local-dmr" element inside standalone.xml.)

* In the `standalone/configuration/standalone.xml` file of your WildFly Server in which you just installed the Hawkular WildFly Agent, set your Hawkular credentials in the storage-adapter XML element.

[source,xml]
----
  <storage-adapter type="HAWKULAR" username="SET_ME" password="SET_ME" /> <1>
----

<1> You need to provide username/password for one Hawkular user. The app server will only show for this user.

TIP: Optional: A single Hawkular WildFly Agent instance can also manage multiple remote WildFly servers. In that case you need to enable a remote-dmr section and specify the username and password of a management user of the remote WildFly Server.

Now you can start the managed WildFly instance, keeping in mind that if you are following this QuickStart your Hawkular Server is probably already running on port 8080, so you need to run this instance on a different port by starting the server with `sh bin/standalone.sh -Djboss.socket.binding.port-offset=100` for instance.
Now if you have correcty set up the agent, it will report into your Hawkular Server at http://localhost:8080/hawkular-ui/app/app-list.


== Troubleshooting
=== Error on starting Hawkular- OutOfMemoryError: unable to create new native thread
This may happen if you use Cassandra embedded with Hawkular on *x systems

Cassandra requires `ulimit` settings that are higher than usual on common *nix distributions. First check your present limits with `ulimit -a` and eventually increase open files to 65535 and max user processes to 4096 as appropriate on your system.

On RHEL, CentOS and Fedora the settings can be made persistent in `/etc/security/limits.conf` like this:
----
[your_username]          hard    nofile          65535
[your_username]          soft    nofile          65535
[your_username]          hard    nproc           4096
[your_username]          soft    nproc           4096
----

where `[your_username]` needs to be replaced by the by the name of the user who starts Hawkular or Cassandra nodes.

=== Unable to resolve realm public key remotely, status = 404

Exception: `ERROR [io.undertow.request] (default task-2) UT005023: Exception handling request to
/hawkular/accounts/personas/current:` `java.lang.RuntimeException: Unable to resolve realm public key remotely, status
= 404`

This happens when the auth server (Keycloak) cannot be reached. Make sure that the authentication server URL is set
to the correct location of the Keycloak server. This might be wrong if you are using the `-b` option to bind
Wildfly to a specific IP or if you have specified a port-offset (`-Djboss.socket.binding.port-offset=123`).

The property to verify is called `auth-server-url` and is located on the following files:
----
$HAWKULAR_HOME/standalone/configuration/standalone.xml
$HAWKULAR_HOME/modules/org/hawkular/nest/main/deployments/hawkular-console.war/keycloak.json
----

=== Can't do anything without a feed; aborting startup: java.lang.RuntimeException: Cannot get tenant ID

Exception: `ERROR [org.hawkular.agent.monitor.service.MonitorService] (Controller Boot Thread) HAWKMONITOR010026:`
`Can't do anything without a feed; aborting startup: java.lang.RuntimeException: Cannot get tenant ID`

Similar to the above: make sure that your auth server (Keycloak) configuration is correct.
