title=Community
descritpion=Downloads bla bla
date=2015-02-04
type=page
tags=blog, asciidoc
status=published
~~~~~~
= Community
Jirka Kremser
2015-02-04



= Components
== Hawkular
Description: The “glue” use all components to build the hawkular solution, this is the project that users would build and run, it consumes all the components.

GitHub link: https://github.com/hawkular/hawkular

JIRA: https://issues.jboss.org/browse/HAWKULAR


== Hawkular Alerts
Description: Model and services to model and define alerts. It also runs the engine to tell when an alert needs to be triggered.

JIRA: https://issues.jboss.org/browse/HWKALERTS

GitHub link: https://github.com/hawkular/hawkular-alerts

== Hawkular Metrics
Description: Model and service for metrics and availability storage.

JIRA: https://issues.jboss.org/browse/HWKMETRICS

GitHub link: https://github.com/hawkular/hawkular-metrics

== Hawkular Bus
Description: Communication back bone

JIRA: https://issues.jboss.org/browse/HWKBUS

GitHub link: https://github.com/hawkular/hawkular-bus

== Hawkular Inventory
Description: In charge of modeling the various components to monitor and their relationships.

JIRA: https://issues.jboss.org/browse/HWKINVENT

GitHub link: https://github.com/hawkular/hawkular-inventory

== Hawkular Build Tools
Description: Various tools to help for the build, contains checkstyle definitions for instance.

JIRA: https://issues.jboss.org/browse/HAWKULAR

GitHub link: https://github.com/hawkular/hawkular-build-tools

= Mailing Lists

* User
https://developer.jboss.org/en/hawkular

* Developer
https://lists.jboss.org/mailman/listinfo/hawkular-dev

* Commits
https://lists.jboss.org/mailman/listinfo/hawkular-commits

image::/img/dependencies.svg[Dependencies,height=300]


= Around the Web
:icons: font

==== IRC Freenode
link:irc://irc.freenode.net/#hawkular[#hawkular]

{empty} +

==== Facebook
icon:facebook[size=2x] {nbsp} https://www.facebook.com/hawkular.io

icon:facebook[size=2x] {nbsp} https://www.facebook.com/hawkular.org

{empty} +

==== Google+
icon:google-plus[size=2x] https://plus.google.com/u/0/b/100667078659222571663/100667078659222571663/about[Hawkular]

{empty} +

==== Twitter
icon:twitter[size=2x] https://twitter.com/hawkular_org[@hawkular_org]

icon:twitter[size=2x] https://twitter.com/hawkular_io[@hawkular_io]
