= Hawkular Inventory 0.15.0.Final - Release
Lukas Krejci
2016-04-27
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, inventory, release

I'm happy to announce the release of Hawkular Inventory 0.15.0.Final.

== Changes

This release was brewing for a long time and brings just 1 important and big 
feature.

=== Inventory Synchronization

To ensure only the minimal amount of work is done when syncing, feeds, 
resource and metric types as well as resources and metrics have now an 
associated "identity hash", which is a Merkle tree hash of the entity's ID, 
important data (depends on entity type) and the hashes of its children. This 
way one can quickly check if a feed reported any new changes since the last 
time - just compare its identity hash with the last value known to you.

You can now describe the structure of the inventory a feed wants to report 
locally on the feed and report it back to inventory server - it will ensure 
that all creates, updates and deletes are applied so that inventory reflects 
what the feed "sees".  

=== Other

Apart from the inventory synchronization there's been a handful of bugfixes 
and improvements and updates to REST documentation that should make it a 
little bit easier to understand (further enhancements are hopefully coming, 
we're still learning how to use swagger in java efficiently ;-) ).

Additionally, the API of canonical paths has been extracted from the inventory
project into Hawkular Commons and lives as a standalone artifact - 
http://origin-repository.jboss.org/nexus/content/repositories/public/org/hawkular/commons/hawkular-inventory-paths/.
This was done to minimize the dependencies between various Hawkular components
that need to use canonical paths.

== Future

In the future releases, we plan to refine the inventory sync further, 
restructure the REST API to get rid of the potential ambiguities and many 
other things.

== Relase Links

Github:: https://github.com/hawkular/hawkular-inventory/releases/tag/0.15.0.Final
Maven Artifacts:: http://origin-repository.jboss.org/nexus/content/repositories/public/org/hawkular/inventory/

== Thanks

Special thanks go out to Justine Tunney, Heiko Rupp, Jirka Kremser, Pavol 
Loffay and Peter Palaga for their contributions to the release.

