= How to develop on Hawkular
Heiko Rupp
2015-02-16
:description: Hacking on Hawkular
:jbake-type: page
:jbake-status: published

== Developing Hawkular

Hawkular is a set of projects and sub-projects developed together and than assembled in the Hawkular integration
project.

The biggest part of the Hawkular server code is written in Java 8.
Project assembly is run via Apache Maven.

The UI code consists mostly of AngularJS directives written in Typescript and then translated into JavaScript.

= Components

== Hawkular

Description: The “glue” use all components to build the hawkular solution, this is the project that users would build and run, it consumes all the components.

GitHub link: https://github.com/hawkular/hawkular

JIRA: https://issues.jboss.org/browse/HAWKULAR


== Hawkular Alerts
Description: Model and services to model and define alerts. It also runs the engine to tell when an alert needs to be triggered.

JIRA: https://issues.jboss.org/browse/HWKALERTS

GitHub link: https://github.com/hawkular/hawkular-alerts

== Hawkular Metrics
Description: Model and service for metrics and availability storage.

JIRA: https://issues.jboss.org/browse/HWKMETRICS

GitHub link: https://github.com/hawkular/hawkular-metrics

== Hawkular Bus
Description: Communication back bone

JIRA: https://issues.jboss.org/browse/HWKBUS

GitHub link: https://github.com/hawkular/hawkular-bus

== Hawkular Inventory
Description: In charge of modeling the various components to monitor and their relationships.

JIRA: https://issues.jboss.org/browse/HWKINVENT

GitHub link: https://github.com/hawkular/hawkular-inventory

== Hawkular Build Tools
Description: Various tools to help for the build, contains checkstyle definitions for instance.

JIRA: https://issues.jboss.org/browse/HAWKULAR

GitHub link: https://github.com/hawkular/hawkular-build-tools
