== Features

=== Metric storage
Hawkular Metrics offers a REST API to store and retrieve metrics. By providing a REST API, any kind of client can connect to the backend to store any kind of metrics.
While Hawkular provides some link:clients.html[clients libraries], the same API can be called with commands line tools like Curl.

Three types of metrics are available

 * Availability metrics:  A Metric that represent an availability: up or down.
 * Counter metrics: Metrics that always go up, like a number of calls ever made to some AP, the total number of snow days...
 * Gauge metrics: A value that can go up or down, like the response time on an application, a temperature...

Depending on the type of metrics, various query methods are available:

 * Rates can be obtained for counter metrics type.
 * Buckets (min/max/average on some intervals) can be obtained for gauges when all datapoints are not needed.

All metrics can have tags for easy filtering and retention time to automatically prune older data.

=== Metrics collection
Through https://github.com/hawkular/hawkular-metrics/tree/master/clients/ptranslator[ptrans network protocol adapter], Hawkular supports metrics collected through:

 * syslog
 * graphite
 * Ganglia
 * StatsD
 * collectD 
 
Additionally Heapster natively has a https://github.com/kubernetes/heapster/tree/master/sinks/hawkular[sink for Hawkular], it allows to collect metrics coming from a Kubernetes environment (container, pods and hosts metrics in general).

=== Alerting

Powerful alerting is a must have in any monitoring system, in general alerting can be used to notify people or to execute operations (restart a machine, autoscale an environment...).

Hawkular Alerts embeds a rule engine but hides the complexity behind a simple REST API.

Multiple kind of conditions can be defined:
 
 * Threshold:  (X < 10, X >= 20)
 * Threshold Range: X inside [10,20), X outside [100,200]
 * Compare two metrics: X < 80% Y
 * String: X starts with "ABC", X matches "A.*B"
 * Availability: X is DOWN
 
When many measurements are made, some measurements may not be relevant and one need to filter noise from real issues. To do so, Hawkular Alerts has various ways for dampening:

 * Strict: N consecutives true conditions are needed before the action is triggered
 * Relaxed counts: N consecutives true conditions out of M measurements
 * Strict time: Condition is true for the time T    
 * Relaxed time: N true conditions in the time T

==== Pluggable action mechanism

Hawkular has notification plugins for:

 * EMails notification
 * Mobile Push notification (through Aerogear UPS)
 * SMS notification (with Twillio)
 
But one can extend and add its own plugin which may take actions rather than notify.

=== Metric Data Visualization
Hawkular Metrics is compatible with Grafana for dashboard-like visualization.
Additionally, Hawkular provides ready to use Angular directives to stick graphs on any HTML page. One can build a customized report in very little time.

=== Security
Multi-tenancy support. Each tenant can set default retention policies that can be changed for each metric that this tenant owns.


=== Inventory
To better react to system failures and/or do root cause analysis, a good understanding of the environment is needed.
Hawkular Inventory provides a graph database designed to store information about how various parts of the architecture are connected together.

A simple REST API allows to record and query how elements are related, it could be deployments in a server, group temperature sensors...

=== Pinger

A service of Hawkular serves at regularly pinging websites, it's a simple mechanism to check if a website is alive and alert in case there are issues, it's used by the console

=== Middleware Management Console

The console is targetted at middleware management (currently JBoss Wildfly only) and reuse all the services mentioned above.