:title: hawkular.github.io

== Web presence of Hawkular

image:https://travis-ci.org/hawkular/hawkular.github.io.svg?branch=pages["Build Status", link="https://travis-ci.org/hawkular/hawkular.github.io"]
image:http://www.issuestats.com/github/hawkular/hawkular.github.io/badge/pr["PR Stats", link="http://www.issuestats.com/github/hawkular/hawkular.github.io"]

=== Description
When pushing a commit into this branch, the site is automatically built and published to http://hawkular.github.io
Most likely the content of the website you are looking for is link:src/main/jbake/content/[here].

=== Building the site on localhost
. `git clone https://github.com/hawkular/hawkular.github.io`
. `git checkout pages`
. Provided Maven is installed, run one of following commands:

* `mvn` Simply runs jbake and generate the site into `target/website` dir.
* `mvn -Pwatch` Polls a folder and run jbake whenever changes happen.
* `mvn -Pinline` Same as -Pwatch, but also launches an embedded winstone container that by default listens on http://localhost:8080. Additionally you may want to use `-Djbake.port=X -Djbake.listenAddress=Y`.

=== Maven Filtering
All `*.adoc` and `*.ftl` files now support maven filtering, so if some property is defined in pom.xml, it can be reused by referencing it as `${property.name}`.
