:title: hawkular.github.io

== Web presence of Hawkular

image:https://travis-ci.org/hawkular/hawkular.github.io.svg?branch=pages["Build Status", link="https://travis-ci.org/hawkular/hawkular.github.io"]

=== Description
When pushing a commit into this branch, the site is automatically built and published to http://hawkular.github.io
Most likely the content of the website you are looking for is link:src/main/jbake/content/[here].

=== Building the site on localhost
. `git clone https://github.com/hawkular/hawkular.github.io`
. `git checkout pages`
. Provided Maven is installed, run one of following commands:

* `mvn jbake:generate` Simply runs jbake and generate the site into `target/website` dir.
* `mvn jbake:watch` Polls a folder and run jbake whenever changes happen.
* `mvn jbake:inline` Same as watch, but also launches an embedded winstone container that by default listens on http://localhost:8080. Additionally you may want to use `-Djbake.port=X` `-Djbake.listenAddress=Y`.

NOTE: `mvn install` will most likely fail on localhost, because it needs the OAuth token for GitHub.
