:title: hawkular.github.io

== Web presence of Hawkular

image:https://travis-ci.org/hawkular/hawkular.github.io.svg?branch=pages["Build Status", link="https://travis-ci.org/hawkular/hawkular.github.io"]
image:http://www.issuestats.com/github/hawkular/hawkular.github.io/badge/pr["PR Stats", link="http://www.issuestats.com/github/hawkular/hawkular.github.io"]

=== Description
When pushing a commit into this branch, the site is automatically built and published to http://hawkular.github.io
Most likely the content of the website you are looking for is link:src/main/jbake/content/[here].

=== Building the site on localhost
. `git clone https://github.com/hawkular/hawkular.github.io`
. `git checkout pages`
. Provided Maven is installed, run one of following commands:

* `mvn` Simply runs jbake and generate the site into `target/website` dir.
* `mvn -Pwatch` Polls a folder and run jbake whenever changes happen.
* `mvn -Pinline` Same as -Pwatch, but also launches an embedded winstone container that by default listens on http://localhost:8080. Additionally you may want to use `-Djbake.port=X -Djbake.listenAddress=Y`.

=== Variable Substitution
All files inside the link:src/main/jbake/templates/[templates] directory can contain `${config.property_name}` and all files in link:src/main/jbake/content/[content] can use `{property_name}`. The key-value pairs are declared in link:src/main/jbake/jbake.properties[jbake.properties] file, so for example with the "property_name" the line would look like `property_name=whatever` (no "config" prefix here).
