= Yet another release of Hawkular, the seventh one !
Thomas Heute
2015-11-19
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, hawkular, release

== What is new?
Hawkular, the monitoring platform, is happy to announce the release of its seventh milestone 1.0.0.Alpha7.

=== Alert Center

More progress on the alert center, with the option to list, search and edit triggers (the rules of the alerts definitions).
Alerts are also more prominent from the resources themselves.

=== UI modifications

Small/medium enhancements to the UI.
Ability to zoom in in a graph for more details.

=== Release notes

Full list of Jira issues fixed in this release:
link:/releasenotes/1.0.0.Alpha7.html[Release Notes - Hawkular - Version 1.0.0.Alpha7]

== Watch the demo online

The Hawkular console demo also includes a preview of Hawkular BTM (Business Transaction Management)

Visit the recording here:

video::ExUnnEuM2zk[youtube,width=600,height=400]

We will announce the next milestone demo on our
https://plus.google.com/+HawkularOrgProject[Google Plus page].

== Downloads

You can download the release here:

* http://download.jboss.org/hawkular/hawkular/1.0.0.Alpha7/hawkular-dist-1.0.0.Alpha7.zip[Hawkular 1.0.0.Alpha7 (zip)]
* http://download.jboss.org/hawkular/hawkular/1.0.0.Alpha7/hawkular-dist-1.0.0.Alpha7.tar.gz[Hawkular 1.0.0.Alpha7 (tar.gz)]

== What's next?

The next Alpha is planned for December 16th, and we are planning to work on the following:

* More stabilization work
* More work on the organizations / multitenancy
* Support agent download from server for installer purposes
* Start of an 'overview' page per app server

== Btw

There is one easter-egg in the release, it's in the demo ;)
