= We are hiring !
Thomas Heute
2016-01-05
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, hawkular, release

Red Hat is hiring a Java sustaining engineer 

== JBoss Operations Network (JON), RHQ and Hawkular

link:https://www.redhat.com/en/technologies/jboss-middleware/operations-network[JBoss Operations Network] is the product that is fully supported by Red Hat, it is currently based on the link:rhq-project.org[RHQ project]. The RHQ project is still being maintained and enhanced while developing link:http://www.hawkular.org[Hawkular].

== Who are we looking for ?

We are looking for a talented Java developer, preferably with Java EE experience willing to help us on RHQ/JBoss Operations Network. You will join the sustaining engineering team and when time allows help on Hawkular as well.

You need to be in a country where link:https://www.redhat.com/en/about/office-locations[Red Hat has a legal entity] but preferably Czech Republic, Poland, India, Mexico...

== What do we offer ?

We offer a great place to work, Red Hat is listed as one of the link:https://www.glassdoor.com/Best-Places-to-Work-LST_KQ0,19.htm[best place to work].

Sustaining engineers get to learn a lot and fast, you will be challenged on many areas of the project, from Cassandra storage to Google Web Toolkit with the help of very talented engineers who will help you grow as a developer. We'll spread the work with the rest of the team depending on what you enjoy doing, what you want to do/learn and things that must be done.

You will be able to work remotely from home, partially or fully.

== How to apply ?

Please link:http://jobs.redhat.com/jobs/descriptions/middleware-software-engineer-management-and-monitoring-brno-jihomoravsky-kraj-czech-republic-job-1-5929970[apply here], you can also contact me directly via direct message link:https://twitter.com/theute[through Twitter] or find me (theute) on IRC Freenode servers.

Best thing you can do is also to create Pull Requests on either of link:https://github.com/hawkular/hawkular[Hawkular] or link:https://github.com/rhq-project/rhq[RHQ] project, this would beat any other reference, if you are looking for ideas, feel free to join #hawkular or #rhq on the IRC Freenode servers.

I'm looking forward to grow the team and deliver more, faster, better, happier, stronger together.
