= Monitoring a Vert.x Application using Hawkular BTM 0.2.0.Final
Gary Brown
2015-07-22
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, btm, demo, vertx

The Hawkular Business Transaction Management (BTM) project has released version https://github.com/hawkular/hawkular-btm/releases/tag/0.2.0.Final[0.2.0.Final]. Some of the new features within this release:

* URI inclusion/exclusion support, allowing business transactions to be filtered based on initial URIs of interest.

* Propagate business transaction name, identified based on inclusion URI, through subsequent fragments for the same business transaction instance.

* Define instrumentation rules for Vert.x (HTTP and EventBus).

For those not familiar with https://http://vertx.io[Vert.x], it is an event driven, polyglot "tool-kit for building reactive applications on the JVM".

To demonstrate the use of Hawkular BTM, to monitor business transactions executing on vert.x, we have created a https://youtu.be/TtAXiYhqTSk[short screencast].

video::TtAXiYhqTSk[youtube]

Feel free to try out the latest release for yourself on your own applications. If you have any questions or comments, please contact us on link:/community/join.html[these channels].

If you have suggestions for features/enhancements, or find any bugs, then please log an issue in the https://issues.jboss.org/browse/HWKBTM[project jira].

