= Hawkular Metrics - 2k Commits
Stefan Negrea
2015-10-05
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, metrics, release


The Hawkular Metrics project reached a nice milestone last week. On Tuesday a pull-request merge commit marked the https://github.com/hawkular/hawkular-metrics/commit/1e04c5219b4eee6da0eab2714e7196a3dc45f0e1[2000th] commit on the master branch of the project.

Here are few other interesting data points about the project:

 * over 25k lines of code (~87% Java)
 * https://github.com/hawkular/hawkular-metrics/commits/master[over 2k commits], https://github.com/hawkular/hawkular-metrics/pulls?q=is%3Aall[over 385 pull requests]
 * https://github.com/hawkular/hawkular-metrics/releases[17 releases] (with a monthly release cadence)
 * https://github.com/hawkular/hawkular-metrics/commit/d725243544e1d692610cf56b7fe0ffdaff3487f8[19 months since first repository commit]
 * https://github.com/hawkular/hawkular-metrics[24 contributors, 35 forks, and 54 stars in Github]

For those not familiar with https://github.com/hawkular/hawkular-metrics/blob/master/README.adoc[Hawkular Metrics], the project is a high performance storage engine for large volume metric data. The project uses Cassandra as a storage engine because of its flexible data model well suited for time-series data storage and linear scalability with no single point of failure.

Hawkular Metrics offers powerful querying, aggregation, and tagging features for gauge, availability, and counter metrics. The data storage was designed with multi-tenancy as a core feature, which is supported out-of-box. The main public API for the project is a clean REST interface.

These https://github.com/hawkular/hawkular-metrics/commits/1e04c5219b4eee6da0eab2714e7196a3dc45f0e1[first 2000 commits] are just the beginning of great things to come in a relatively young project. There are plans to add additional metric types and more complex statistical and querying capabilities. Ingestion data aggregation, cross metric down-sampling, and rich tagging queries over tag data are just a few of the features we have planned. So far we have been very careful introducing features in order to keep a API clean and deliver robust software.

We welcome all contributions and input. If you or your organization is looking for a metric storage engine, we would love to talk with you. We want to learn about your use case, how you approach metric storage, and if there features are missing in Hawkular Metrics for your particular application.  A good resource for future plans as well as past releases is the https://issues.jboss.org/projects/HWKMETRICS?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page&status=all[Hawkular Metrics JIRA]. Feel free to contact us overy irc (#hawkular on freenode), https://lists.jboss.org/mailman/listinfo/hawkular-dev[mailing list], or email.

As a closing, I want to send a big “Thank You” to the http://www.hawkular.org/[Hawkular organization] for hosting the project and to all the project committers for their outstanding contributions:  https://github.com/tsegismont[Thomas Segismont], https://github.com/stefannegrea[Stefan Negrea], https://github.com/jsanda[John Sanda], https://github.com/mtho11[Mike Thompson], https://github.com/pilhuhn[Heiko Rupp], https://github.com/burmanm[Micheal Burman], https://github.com/mwringe[Matt Wringe], https://github.com/ppalaga[Peter Palaga], https://github.com/jkandasa[Jeeva Kandasamy], https://github.com/heiko-braun[Heiko Braun], https://github.com/Jiri-Kremser[Jirka Kremser], https://github.com/vnugent[Viet Nguyen], https://github.com/jimmidyson[Jimmi Dyson], https://github.com/aslakknutsen[Aslak Knutsen], https://github.com/jpkrohling[Juraci Paixão Kröhling], https://github.com/theute[Thomas Heute], https://github.com/jshaughn[Jay Shaughnessy], https://github.com/metlos[Lukas Krejci], https://github.com/jstrachan[James Strachan], https://github.com/gkhachik[Garik Khachikyan], https://github.com/spadgett[Sam Padgett], https://github.com/vrockai[Villiam Rockai], https://github.com/jmazzitelli[John Mazzitelli], https://github.com/ammendonca[Alexandre Mendonça].

To 4000 commits in half the time!
