= Installation Guide
Thomas Segismont
2015-08-26
:description: Hawkular Metrics standalone installation instructions
:icons: font
:jbake-type: page
:jbake-status: published
:jbake-tags: hawkular-metrics, metrics, installation, cassandra

This guide will help you to install a standalone Metrics server as well as PTrans.

== Prerequisites

=== Java 8

You need a Java Virtual Machine compatible with Java 8.
Hawkular Metrics runs on the OpenJDK or Oracle runtime environment.

Other Java 8 compatible runtime environments _should_ work as well.

=== Apache Cassandra

Hawkular Metrics relies on https://cassandra.apache.org/[Apache Cassandra] for data storage.

IMPORTANT: Cassandra 2.2.2 or later is required. It is recommended to use the latest 2.2.x release if possible.

IMPORTANT: Cassandra 2.1.x is no longer supported.

You may download a distribution zip file from the http://cassandra.apache.org/download/[Apache Cassandra download] page.
You could also use the Datastax community packages for:

* http://docs.datastax.com/en/cassandra/2.2/cassandra/install/installRHEL.html[RHEL-based systems]
* http://docs.datastax.com/en/cassandra/2.2/cassandra/install/installDeb.html[Debian-based systems]
* http://docs.datastax.com/en/cassandra_win/2.2/cassandra/install/installTOC.html[Windows].
* For OS/X you can install Cassandra via http://brew.sh[Homebrew]


== Installing the server

http://wildfly.org/downloads/[Download a Wildfly 10] archive and expand it somewhere on your disk.

Check out the https://github.com/hawkular/hawkular-metrics/releases[Metrics releases] page and download the latest
version of the web application archive: `hawkular-metrics-api-jaxrs-X.Y.Z.war`

Copy `hawkular-metrics-api-jaxrs-X.Y.Z.war` to the `standalone/deployments` directory of the Wildfly server.

Eventually start the server with `bin/standalone.sh`.

== Installing PTrans

Check out the https://github.com/hawkular/hawkular-metrics/releases[Metrics releases] page and download the latest
version of the PTrans distribution archive: `ptrans-X.Y.Z-dist.zip`. Expand it somewhere on your disk.

You can start PTrans with the following command: `java -jar ptrans-all.jar -c <path to ptrans.conf>`
