= Client Configuration Guide
Gary Brown
2015-06-30
:description: Hawkular Business Transaction Management
:icons: font
:jbake-type: page
:jbake-status: published
:toc: macro
:toc-title:

toc::[]

== Configuring a Client Environment

This section will help you to configure a JVM based client environment to instrument a business application and send business transaction fragment (trace) data to the BTM server.

First step is to obtain the BTM distribution. If you have not already done so, then see the instructions on the link:serverinstall.html[Server Installation] page.

Once the BTM distribution zip has been unpacked, you will find a folder called *_btm_*. This folder contains the necessary environment script, jar and instrumentation configuration files to configure a client JVM environment. 

This section will explain how to use the supplied environment script, to setup the necessary client configuration, before starting the JVM. However if you would prefer to integrate this environment into your application/container configuration, then simply copy the entries from the contained *_env.sh_* script, moving the jar and configuration files into appropriate locations.

First step is to setup the *_BTM_HOME_* environment variable to point to the *_btm_* folder in the unpacked BTM distribution.

[source,shell]
----
export BTM_HOME=<btm-distribution-location>/btm
----

Once that is done, then simply run the *_env.sh_* script:

[source,shell]
----
. $BTM_HOME/client/env.sh
----

This sets the _JAVA_OPTS_ environment variable with the appropriate arguments to instrument any technology for which instrumentation rules have been defined.

=== Properties

The properties that can be supplied to the client collector mechanism are:

|===
| Name | Description

| hawkular-btm.config | This property is used to locate either a configuration file, or a directory containing multiple configuration files. These files are a JSON representation of the client configuration, containing instrumentation rules. The default value is the _client/config_ directory within the BTM distribution.
| hawkular-btm.base-uri | The URI for the BTM server. The default value is _http://localhost:8180/hawkular/btm_.
| hawkular-btm.username | The username to use with the REST client when communicating with the BTM server. The default is _jdoe_.
| hawkular-btm.password | The password to use with the REST client when communicating with the BTM server. The default is _password_.
| hawkular-btm.log.level | The logging level to use when reporting client collector information to the console (uses Java Util Logging levels. The default is _INFO_.
|===

=== Container Specific Configuration

Although the steps above will work in many situations (e.g. Java standalone, Apache Tomcat), some environments have tighter control over the classpath made available to the business applications. Therefore some additional container specific configuration will be required.

==== Wildfly

Wildfly requires any 'system packages', that need to be generally accessible by any application, to be defined in a system property called *_jboss.modules.system.pkgs_*.

This property has been preconfigured in the *_env.sh_* script so no additional actions are required. However it has been described to highlight the additional step that was required.

==== Karaf

Edit the *_etc/config.properties_* file, within the Karaf installation, and append the following to the _org.osgi.framework.bootdelegation_ property:

[source,shell]
----
org.osgi.framework.bootdelegation=...,org.jboss.byteman.*

----

== Instrumented Technologies

This section lists the technologies that have instrumentation rules defined:

* Apache Camel (core only, but this provides details of various components that are called)
* HTTP clients
** Java HttpURLConnection
** Apache httpclient
** RESTEasy JAX-RS client
* JMS
* Servlet
* Restlet
* JDBC
* SwitchYard


