= Hawkular BTM Documentation
Gary Brown
2015-06-30
:icons: font
:jbake-type: page
:jbake-status: published
:toc: macro
:toc-title:

toc::[]

== What is ...?

Since the project began, with the initial focus on "Business Transaction Management" (hence the name), the scope has expanded to include Application Performance Management and more recently Distributed Tracing. So it is worth initially explaining the different areas:

==== Application Performance Management

As defined on https://en.wikipedia.org/wiki/Application_performance_management[wikipedia], "application performance management  (APM)  is the monitoring and management of performance and availability of software applications. APM strives to detect and diagnose complex application performance problems to maintain an expected level of service".

The focus of this area is on the performance of the parts, whether at the application, service, resource or internal component level. So can be viewed as equivalent to a profiling tool for distributed systems.

==== Distributed Tracing

Distributed tracing is concerned with recording and analysing the path(s) taken from an initial invocation as it cascades across a distributed system, primarily as a diagnostic aid to developers and operation teams.

The focus of this area is on the communication paths of individual or multiple (aggregated) invocations across a distributed system, to view the performance profile of the various components along those paths.

==== Business Transaction Management

Business Transaction Management can actually be considered an extension of Distributed Tracing. Both are concerned with the tracing of invocations across potentially multiple distributed services. The difference is that Business Transaction Management is more concerned with the business relevance of the paths taken, and the business metrics that can be obtained and analysed.

It is also worth clarifying the term *Business Transaction* - according to one website footnote:[http://smallbusiness.chron.com/business-transaction-definition-examples-25244.html], _"The accounting definition of a business transaction, according to the online Business Dictionary, is "an economic event that initiates the accounting process of recording it in a company's accounting system." This is the official definition. However, selling an item at a garage sale where no accounting system is in place also can be a business transaction"_.

We prefer to use a more general definition of a Business Transaction. It can be any interactions within a business, or between a business and its customers/partners, that results in direct or indirect value. For example, making an enquiry to obtain information about a item, such as its description or stock level, has no associated economic event. However it may be a necessary precursor to someone considering a purchase, and provide invaluable insight into the browsing patterns of its customer base.

Once we have a definition for a Business Transaction, the next thing to understand is a *Business Transaction Instance*. This is a single occurrance of what is understood to be a Business Transaction. So for example, a person buying a item (e.g. a computer), on a particular day and time, would result in a Business Transaction Instance.


== Overview

The architecture of Hawkular BTM is very simple. It comprises of clients that are being monitored, reporting information to a server for analysis, where the results are then presented to users via a User Interface.

=== The Clients

Execution environments (clients), that are responsible for executing business applications, are instrumented to collect information about the service invocations and report it to the Hawkular BTM Server.

The instrumentation mechanism uses the fantastic http://byteman.jboss.org[ByteMan] project to instrument any JVM based application to obtain the information required, *without any changes to the application or frameworks being monitored*.

Typically a business application will involve more than one server, executing different parts of the application - and therefore a single business transaction instance may be comprised of multiple trace fragments collected from different locations. It is the responsibility of the client instrumentation to describe both the structure of the business transaction instance fragment executing in a particular server, and also capture information that will enable the transaction instance to be traced across servers.

Currently tested client environments include:

* Standalone JVM (e.g. micro services running outside traditional containers)
* Wildfly and JBoss EAP JEE server
* Apache Tomcat
* Apache Karaf OSGI container

Instructions on how to configure the client environment can be found here: link:clientconfig.html[Client Configuration]

=== The Server

The Hawkular BTM Server supports reporting and analysis of the business transaction data. These capabilities can be accessed through a set of REST services, more information can be found here: link:../../rest/rest-btm.html[BTM REST services]

The instructions for installing the server can be found here: link:serverinstall.html[Server Installation]

=== The User Interface

The Hawkular BTM User Interface provides the capability to:

* View Application Performance information

* View Distributed Tracing

* Manage Business Transactions
** Configure business transaction definitions
** View a list of business transactions, with summary statistics
** Access more detailed analytics for the business transactions

These capabilities will be discussed in more detail in the following section.


== Console

Once the server has been installed, and started, you will be able to start up the user interface by pointing a browser to: http://localhost:<port>

_Where 'port' is the port used by the server (e.g. 8180 if port offset of 100 has been used)._

If the server was initially started by importing the development account details, then the default username and password is *_jdoe_* and *_password_*. However, if the server is started without importing any predefined users, then it will be necessary to register any required users by selecting the appropriate link on the login page.

=== Application Performance

This page shows Application Performance Management information related to the applications and their components being monitored.

The lefthand side of the page provides a collapsible sidebar with various filters that can be applied to the information being viewed. This is explained in more detail in a later section.

The graph shows aggregated durations for the component types being monitored, at the defined intervals. The interval can be changed using the dropdown at the top of the graph.

The table presents the performance information aggregated based on the component type (e.g. Database, EJB, Consumer, etc), URI and (if relevant) operation name.

The metrics provided are _count_ (the number of activity records aggregated), the _elapsed_ time and _actual_ time. The _elapsed_ time represents the total time spent within a particular component (including calls to child components). The _actual_ time represents only the time specific in the component itself.

This information can be used to identify performance bottlenecks within an application. Using details about the amount of 'actual' time specific within a component, combined with the number of times it is invoked, can help locate the best opportunities for making performance improvements.

=== Distributed Tracing

This page shows a graphical representation of the path taken by interactions through a set of distributed services.

The lefthand side of the page provides a collapsible sidebar with various filters that can be applied to the information being viewed. This is explained in more detail in a later section.

At the top of the graph is a dropdown providing a list of initial (root) nodes for the paths that can be displayed. Once a path is selected, the invocation path will be displayed as a set of connected nodes.

Each node reflects its severity as a colour, ranging from _green_ meaning performing well, up to _red_ indicating an area for further investigation.

The nodes also provide information about the average duration spent in the node, the number of times the node has been invoked, and provides a tooltip with more detailed stats.

The links also provide information about the number of invocations, and a tooltip with more detailed stats.

The graph can be zoomed and scrolled to view the relevant parts of the information. There is a 'reset zoom' button to return to the original (initial) version of the graph.


=== Filter Sidebar

On the lefthand side of some of the UI pages (Application Performance and Distributed Tracing currently) is an area for specifying filters that can be used to limit the information being viewed.

The _Business Transaction_ list will include any business transactions that have been defined. This can be used to focus the Application Performance information just on a specific business transaction to help identify performance bottlenecks.

The _Properties_ section enables properties associated with business transactions to be used to define inclusion or exclusion filters. The name of the property can be selected from a dropdown.

The _Faults_ section enables the data to be limited based on the inclusion or exclusion of a particular fault within the observed data.

The _Text_ field is only applicable to the Application Performance page, and focuses the table rows on entries that contain the specified text.

The _Host Name_ filter can be used to focus on data associated with a particular host.


=== Business Transactions

==== Overview

This page shows information about the business transactions, separated into tabs for the following categories.

===== Managed

This tab shows summary statistics for a list of actively managed or disabled business transactions.

On the left of the page is two pie charts representing the transaction and fault counts across the business transactions.

Each business transaction is further presented with the following statistics:

* The number of completed instances of the business transaction (per hour)

* The completion time 95 percentile (per hour)

* The number of instances that completed with faults (per hour)

For each business transaction:

* Users can navigate to the detailed statistical information about the business transaction by selecting the transactions names.

* Selecting the cog icon will take the user to the business transaction's configuration page.

* The trash icon is used to delete the business transaction.


===== Candidates

The candidates tab is used to identify interactions (associated with URIs) that have not currently be associated with a business transaction. When new URIs are detected, a red flag symbol will appear next to the _Candidates_ tab name.

At the top of the page, it is possible to either enter the name of a new business transaction, or select one of the existing business transactions from a drop down list. Once a name has been entered, or existing one selected, then the list of URIs will become enabled.

The user can select zero or more of the URIs that are appropriate for the business transaction. These URIs will be used to create _inclusion filters (regular expressions)_ that will enable the interactions associated with those URIs to be allocated to the business transaction.

To avoid having an extremely long list of URIs, where a REST call involves a URI with one or more path parameters, the system will attempt to identify common patterns, and where found, present a single URI with the '*' meta character in place of the path segment associated with a parameter. If the user selects such a URI to be associated with a business transaction, this will result in an 'evaluate URI' action automatically being defined, to extract the path parameter(s). An effort is made to infer the name of the parameter(s), but these may need to be manually edited to define a meaningful name.

If a new business transaction is being created, then the user can click either the *_Manage_* or *_Ignore_* buttons. This will determine the initial reporting level of the business transaction, as to whether instances of this transaction will be reported to the server (i.e. managed) or not (i.e. ignored).

If an existing business transaction is selected, then pressing the *_Update_* button will associate the inclusion filter for any checked URIs with the existing business transaction.

Whichever button is selected, the user will be taken to the configuration page for the business transaction. See the following section for information on how to configure the business transaction.


===== Ignored

This tab lists the business transactions that are being ignored.

This state exists to enable business transaction instances to be categorised, and permanently marked as not being of interest. By explicitly identifying even business interactions that are not of interest, it is possible to detect any new traffic that may occur that has not previously be categorised, which informs the administrators that attention is required to investigate the unfamilar interactions.


==== Configuration

Whenever changes are saved, or the form is initially displayed, any validation errors will be displayed. Errors will also be highlighted on the form, by the appropriate field labels being displayed in red.

The configuration for a business transaction is separated into three sections.

===== Description

Simply enables the user to provide a description of the business transaction and its scope (in case it incorporates a number of different invocations).

===== Filters

The filters section defines the link between the transaction instances, performed on specific URIs, and the business transaction name.

This is achieved by defining one or more inclusion filter regular expressions that may match a URI. Once a URI is matched against one of the inclusion filters, it may then be matched against the exclusion filter regular expressions (if defined) to determine if a subset of the included URIs should be excluded.

Once a transaction instance has been associated with a business transaction, the _Reporting Level_ is used to determine how that business transaction instance should be handled.

.Reporting Levels
|===
|Level |Description

|All |This level means that all information about the business transaction should be reported

|None | This means that the business transaction is temporarily disabled so no information should be reported

|Ignore | This means that the business transaction is permanently disabled so not of interest

|===

===== Processors

Out of the box, Hawkular BTM is configured with instrumentation rules for a selection of technologies, that can used to monitor generic information about business transaction instances executing over those technologies.

However, to make this information more useful in a business context, it is important to also be able to extract relevant details from the business messages, to aid future analysis. This section will explain how the additional "business transaction specific configuration" can be provided.

Zero or more processors can be defined for a business transaction. If none are defined, then the business transaction configuration will simply be used to associate specific interactions with the business transaction name.

If a processor is defined, it is comprised of an initial set of parameters to identify which specific node(s) in the business transaction call trace are to be processed, and then a set of actions that should be performed. The actions will be discussed further down.

.Processor Criteria
|===
|Field |Description

|Node Type |This field identifies the type of call trace _node_ that the processor will be applied to, with possible values of _Consumer_, _Producer_ or _Component_

|Direction |The direction the interaction being processed will flow, either _In_ or _Out_

|URI Filter |Regular expression that can optionally be defined to isolate the nodes of interest, where multiple nodes of the same type may occur within the same transaction instance

|Operation |For _Component_ node types, the optional operation name can be used to identify a specific node in the call trace

|Predicate |A predicate can be defined to provide finer grained filtering on whether the processor should be applied to a particular call trace node, which by default is not specified

|===

As mentioned, each processor can define multiple actions to be performed on nodes that meet the criteria associated with the processor.

Each action can also be guarded by its own predicate, so that not all actions will be performed for each node that passes the processor's overall criteria. The default is no predicate for the actions.

The fields that need to be defined for an action will be specific to the action type, and therefore are listed in the description fields for the action:

.Actions
|===
|Action Type |Description

|Add Content |Include content in the business transaction fragment node. Fields are '*_name_*' to distinguish content if multiple entries will be defined, '*_type_*' to classify the content type, and an expression (see below) to determine how the content is derived

|Add Correlation Identifier |Define correlation identifier used to correlate the current fragment with other fragments based on business context. The '*_scope_*' field can have values _Global_, _Local_ (only relevant in the current service/app) or _Interaction_ (scoped to the single interaction, i.e. shared between the communicating endpoints). The expression (see below) determines how the value is derived.

|Evaluate URI |Apply a template to the URI to extract path and query parameters, e.g. /customer/{customerId} or /orders?{id}

|Set Detail |Extract a node specific value. The '*_name_*' field represents the name associated with the detail, and  an expression (see below) to determine how the value is derived

|Set Fault Code |Define a fault code value. The expression (see below) determines how the value is derived

|Set Fault Description |Define a fault description value. The expression (see below) determines how the value is derived

|Set Property |Extract a named business property. The '*_name_*' field names the business property, and the expression (see below) determines how the value is derived

|===


.Expressions (for Predicates and Values)
|===
|Expression Type | Description

|Literal | A literal value

|XML | XPath expression applied to a XML document. The _Source_ field identifies where the information is obtained from (e.g. Content, Header). The _Key_ is dependent upon the source, if _Content_ then the key represents the index in an array of arguments, if _Header_ then the key is the header property name.

|JSON | JSONPath Expression applied to a JSON document. The _Source_ field identifies where the information is obtained from (e.g. Content, Header). The _Key_ is dependent upon the source, if _Content_ then the key represents the index in an array of arguments, if _Header_ then the key is the header property name.

|Text | Converts a value into text form. The _Source_ field identifies where the information is obtained from (e.g. Content, Header). The _Key_ is dependent upon the source, if _Content_ then the key represents the index in an array of arguments, if _Header_ then the key is the header property name.

|FreeForm | A MVEL expression (should only be used with extreme caution, as may be subject to change in the future). 

|===



== Properties

The system wide properties are now defined within a single *_btm.json_* file that is included within the _standalone/data/btmconfig_ folder of the BTM server.

The current properties that can be configured here are:

.BTM Properties
|===
|Property Name | Default | Description

|hawkular-btm.collector.onlynamed | false | Determine whether only business transaction fragments associated with a business transaction name should be reported.

|===

WARNING: The _hawkular-btm.collector.onlynamed_ property may be withdrawn in a future release, as it is now possible to name and ignore business transactions. Having the unnamed transactions reported to the server allows changes to be detected and administrators to determine if changes are required.


== Useful Links

. link:serverinstall.html[Server Installation]

. link:clientconfig.html[Client Configuration]

. link:btmrtgov.html[BTM/RTGov Integration]

