= Business Transaction Management Documentation
Gary Brown
2015-06-30
:icons: font
:jbake-type: page
:jbake-status: published
:toc: macro
:toc-title:

toc::[]

== What is ...?

Firstly let us start with what is a *Business Transaction* - according to one website footnote:[http://smallbusiness.chron.com/business-transaction-definition-examples-25244.html], _"The accounting definition of a business transaction, according to the online Business Dictionary, is "an economic event that initiates the accounting process of recording it in a company's accounting system." This is the official definition. However, selling an item at a garage sale where no accounting system is in place also can be a business transaction"_.

I would be even more general, and say that a Business Transaction can be any interactions within a business, or between a business and its customers/partners, to achieve some necessary business objective.

Once we have a definition for a Business Transaction, the next thing to understand is a *Business Transaction Instance*. This is a single occurrance of what is understood to be a Business Transaction. So for example, a person buying a item (e.g. a computer), on a particular day and time, would result in a Business Transaction Instance.

*Business Transaction Management* (BTM), also known as *Application Performance Management*, is the monitoring and analysis of the Business Transaction Instances. By recording the individual transaction instances that occur, users are able to:

- visualise any particular instance to understand which path it took through the Business Transaction,
- analyse the response and latency times associated with the individual transaction instance, which may be necessary to determine if specific Service Level Agreements (SLAs) have been violated
- aggregate a set of instances, based on various criteria, to understand how the Business Transaction operates in different situations, thus helping to make the Business Transaction more efficient
 

== Overview

The architecture of the Business Transaction Management (BTM) solution is very simple. It comprises of clients that are being monitored, reporting information to a server for analysis, where the results are then presented to users via a User Interface.

=== The Clients

Execution environments (clients), that are responsible for executing business applications, are instrumented to allow a trace of those business transaction instances to be recorded to the Business Transaction Management Server.

Our BTM solution uses the fantastic http://byteman.jboss.org[ByteMan] project to instrument any JVM based application to obtain the information required, *without any changes to the application being monitored*.

Typically a business application will involve more than one server, executing different parts of the application - and therefore a single business transaction instance may be comprised of multiple trace fragments collected from different locations. It is the responsibility of the client instrumentation to describe both the structure of the business transaction instance fragment executing in a particular server, and also capture information that will enable the transaction instance to be traced across servers.

Currently tested client environments include:

* Standalone JVM (e.g. micro services running outside traditional containers)
* Wildfly and JBoss EAP JEE server
* Apache Tomcat
* Apache Karaf OSGI container

Instructions on how to configure the client environment can be found here: link:clientconfig.html[Client Configuration]

=== The Server

The Business Transaction Management (BTM) Server supports reporting and analysis of the business transaction data. These capabilities can be access through a set of REST services, more information can be found here: link:../../rest/rest-btm.html[BTM REST services]

CAUTION: The standalone server does not currently support a clustered configuration.

The instructions for installing the server can be found here: link:serverinstall.html[Server Installation]

=== The User Interface

The BTM User Interface provides the capability to:

* Configure business transactions

* View a list of business transactions, with summary statistics

* Access more detailed analytics for the business transactions

These capabilities will be discussed in more detail in the following section.


== Console

Once the server has been installed, and started, you will be able to start up the user interface by pointing a browser to: http://localhost:<port>/hawkular-ui/btm

_Where 'port' is the port used by the server (e.g. 8180 if port offset of 100 has been used)._

The default username and password when first starting the server is *_jdoe_* and *_password_*.

=== Business Transaction List

The initial page of the BTM console shows information about the business transactions, separated into tabs for the following categories.

==== Active

This tab shows summary statistics for a list of actively managed business transactions.

The statistics include:

* The number of completed instances of the business transaction (per hour)

* The completion time 95 percentile (per hour)

* The number of instances that completed with faults (per hour)

* The number of alerts associated with this business transaction

NOTE: The alerts count is currently a placeholder, awaiting integration with the Alerts mechanism.

For each business transaction:

* Users can navigate to the detailed statistical information about the business transaction by selecting the transactions names. NOTE: This page is currently blank and will provide some content in the next release.

* Selecting the cog icon will take the user to the business transaction's configuration page.

* The trash icon is used to delete the business transaction.


==== Candidates

The candidates tab is used to identify interactions (associated with URIs) that have not currently be associated with a business transaction. When new URIs are detected, a red flag symbol will appear next to the _Candidates_ tab name.

At the top of the page, it is possible to either enter the name of a new business transaction, or select one of the existing business transactions from a drop down list. Once a name has been entered, or existing one selected, then the list of URIs will become enabled.

The user can select zero or more of the URIs that are appropriate for the business transaction. These URIs will be used to create _inclusion filters (regular expressions)_ that will enable the interactions associated with those URIs to be allocated to the business transaction.

If a new business transaction is being created, then the user can click either the *_Manage_* or *_Ignore_* buttons. This will determine the initial reporting level of the business transaction, as to whether instances of this transaction will be reported to the server (i.e. managed) or not (i.e. ignored).

If an existing business transaction is selected, then pressing the *_Update_* button will associate the inclusion filter for any checked URIs with the existing business transaction.

Whichever button is selected, the user will be taken to the configuration page for the business transaction. See the following section for information on how to configure the business transaction.


==== Disabled

This tab lists the business transactions that have a reporting level of _None_.

When in this mode, reporting of instance information about the business transaction will be suspended. This is considered to be a temporary state, unlike the following 'Ignored' state which is generally reserved for transactions that will never be of interest.


==== Ignored

This tab lists the business transactoins that are being ignored.

This state exists to enable business transaction instances to be categorised, and permanently marked as not being of interest. By explicitly identifying even business interactions that are not of interest, it is possible to detect any new traffic that may occur that has not previously be categorised, which informs the administrators that attention is required to investigate the unfamilar interactions.


=== Business Transaction Configuration

The configuration for a business transaction is separated into three sections.

==== Description

Simply enables the user to provide a description of the business transaction and its scope (in case it incorporates a number of different invocations).

==== Filters

The filters section defines the link between the transaction instances, performed on specific URIs, and the business transaction name.

This is achieved by defining one or more inclusion filter regular expressions that may match a URI. Once a URI is matched against one of the inclusion filters, it may then be matched against the exclusion filter regular expressions (if defined) to determine if a subset of the included URIs should be excluded.

Once a transaction instance has been associated with a business transaction, the _Reporting Level_ is used to determine how that business transaction instance should be handled.

.Reporting Levels
|===
|Level |Description

|All |This level means that all information about the business transaction should be reported

|None | This means that the business transaction is temporarily disabled so no information should be reported

|Ignore | This means that the business transaction is permanently disabled so not of interest

|===

==== Processors

Out of the box, BTM is configured with instrumentation rules for a selection of technologies, that can used to monitor generic information about business transaction instances executing over those technologies.

However, to make this information more useful in a business context, it is important to also be able to extract relevant details from the business messages, to aid future analysis. This section will explain how the additional "business transaction specific configuration" can be provided.

Zero or more processors can be defined for a business transaction. If none are defined, then the business transaction configuration will simply be used to associate specific interactions with the business transaction name.

If a processor is defined, it is comprised of an initial set of parameters to identify which specific node(s) in the business transaction call trace are to be processed, and then a set of actions that should be performed. The actions will be discussed further down.

.Processor Criteria
|===
|Field |Description

|Node Type |This field identifies the type of call trace _node_ that the processor will be applied to, with possible values of _Consumer_, _Producer_ or _Component_

|Direction |The direction the interaction being processed will flow, either _In_ or _Out_

|URI Filter |Regular expression that can optionally be defined to isolate the nodes of interest, where multiple nodes of the same type may occur within the same transaction instance

|Operation |For _Component_ node types, the optional operation name can be used to identify a specific node in the call trace

|Predicate |A predicate can be defined to provide finer grained filtering on whether the processor should be applied to a particular call trace node, which by default is not specified

|===

As mentioned, each processor can define multiple actions to be performed on nodes that meet the criteria associated with the processor.

Each action can also be guarded by its own predicate, so that not all actions will be performed for each node that passes the processor's overall criteria. The default is no predicate for the actions.

The fields that need to be defined for an action will be specific to the action type, and therefore are listed in the description fields for the action:

.Actions
|===
|Action Type |Description

|Add Content |Include content in the business transaction fragment node. Fields are '*_name_*' to distinguish content if multiple entries will be defined, '*_type_*' to classify the content type, and an expression (see below) to determine how the content is derived

|Add Correlation Identifier |Define correlation identifier used to correlate the current fragment with other fragments based on business context. The '*_scope_*' field can have values _Global_, _Local_ (only relevant in the current service/app) or _Interaction_ (scoped to the single interaction, i.e. shared between the communicating endpoints). The expression (see below) determines how the value is derived.

|Evaluate URI |Apply a template to the URI to extract path and query parameters, e.g. /customer/{customerId} or /orders?{id}

|Set Detail |Extract a node specific value. The '*_name_*' field represents the name associated with the detail, and  an expression (see below) to determine how the value is derived

|Set Fault Code |Define a fault code value. The expression (see below) determines how the value is derived

|Set Fault Description |Define a fault description value. The expression (see below) determines how the value is derived

|Set Property |Extract a named business property. The '*_name_*' field names the business property, and the expression (see below) determines how the value is derived

|===


.Expressions (for Predicates and Values)
|===
|Expression Type | Description

|Literal | A literal value

|XML | XPath expression applied to a XML document. The _Source_ field identifies where the information is obtained from (e.g. Content, Header). The _Key_ is dependent upon the source, if _Content_ then the key represents the index in an array of arguments, if _Header_ then the key is the header property name.

|JSON | JSONPath Expression applied to a JSON document. The _Source_ field identifies where the information is obtained from (e.g. Content, Header). The _Key_ is dependent upon the source, if _Content_ then the key represents the index in an array of arguments, if _Header_ then the key is the header property name.

|Text | Converts a value into text form. The _Source_ field identifies where the information is obtained from (e.g. Content, Header). The _Key_ is dependent upon the source, if _Content_ then the key represents the index in an array of arguments, if _Header_ then the key is the header property name.

|FreeForm | A MVEL expression (should only be used with extreme caution, as may be subject to change in the future). 

|===


=== Kibana analytics dashboard

The UI provides access to the Kibana analytics dashboard, showing the completion time information derived from the executing business transaction instances, by selecting the _View Analytics_ button on the top right corner of the Business Transaction page.

Some tips on using Kibana:

* The 'filters' green tab at the top of the page can be expanded to show the current filters that have been applied. Whenever you select a time region (from the top chart), or select a magnifying glass or no entry icon, this will cause the information being viewed to be further constrained by adding an additional filter. When you wish to revert back to a previous level of information, simply remove (or disable) the particular filter box.

* In the lower table, showing the latest response time 'records', you can select the fields in the left hand column to get further statistics regarding the different values.

Further information on using Kibana can be found here: https://www.elastic.co/guide/en/kibana/3.0/index.html



== Properties

The system wide properties are now defined within a single *_btm.json_* file that is included within the _standalone/data/btmconfig_ folder of the BTM server.

The current properties that can be configured here are:

.BTM Properties
|===
|Property Name | Default | Description

|hawkular-btm.collector.onlynamed | false | Determine whether only business transaction fragments associated with a business transaction name should be reported.

|===

WARNING: The _hawkular-btm.collector.onlynamed_ property may be withdrawn in a future release, as it is now possible to name and ignore business transactions. Having the unnamed transactions reported to the server allows changes to be detected and administrators to determine if changes are required.


== Useful Links

. link:serverinstall.html[Server Installation]

. link:clientconfig.html[Client Configuration]

. link:btmrtgov.html[BTM/RTGov Integration]

