= Business Transaction Management Documentation
Gary Brown
2015-06-30
:icons: font
:jbake-type: page
:jbake-status: published
:toc: macro
:toc-title:

toc::[]

== What is ...?

Firstly let us start with what is a *Business Transaction* - according to one website footnote:[http://smallbusiness.chron.com/business-transaction-definition-examples-25244.html], _"The accounting definition of a business transaction, according to the online Business Dictionary, is "an economic event that initiates the accounting process of recording it in a company's accounting system." This is the official definition. However, selling an item at a garage sale where no accounting system is in place also can be a business transaction"_.

I would be even more general, and say that a Business Transaction can be any interactions within a business, or between a business and its customers/partners, to achieve some necessary business objective.

Once we have a definition for a Business Transaction, the next thing to understand is a *Business Transaction Instance*. This is a single occurrance of what is understood to be a Business Transaction. So for example, a person buying a item (e.g. a computer), on a particular day and time, would result in a Business Transaction Instance.

*Business Transaction Management* (BTM), also known as *Application Performance Management*, is the monitoring and analysis of the Business Transaction Instances. By recording the individual transaction instances that occur, users are able to:

- visualise any particular instance to understand which path it took through the Business Transaction,
- analyse the response and latency times associated with the individual transaction instance, which may be necessary to determine if specific Service Level Agreements (SLAs) have been violated
- aggregate a set of instances, based on various criteria, to understand how the Business Transaction operates in different situations, thus helping to make the Business Transaction more efficient
 

== Overview

The architecture of the Business Transaction Management (BTM) solution is very simple. It comprises of clients that are being monitored, reporting information to a server for analysis, where the results are then presented to users via a User Interface.

=== The Clients

Execution environments (clients), that are responsible for executing business applications, are instrumented to allow a trace of those business transaction instances to be recorded to the Business Transaction Management Server.

Our BTM solution uses the fantastic http://byteman.jboss.org[ByteMan] project to instrument any JVM based application to obtain the information required, *without any changes to the application being monitored*.

Typically a business application will involve more than one server, executing different parts of the application - and therefore a single business transaction instance may be comprised of multiple trace fragments collected from different locations. It is the responsibility of the client instrumentation to describe both the structure of the business transaction instance fragment executing in a particular server, and also capture information that will enable the transaction instance to be traced across servers.

Currently tested client environments include:

* Standalone JVM (e.g. micro services running outside traditional containers)
* Wildfly JEE server
* Apache Tomcat
* Apache Karaf OSGI container

Instructions on how to configure the client environment can be found here: link:clientconfig.html[Client Configuration]

=== The Server

The Business Transaction Management (BTM) Server supports reporting and analysis of the business transaction data. These capabilities can be access through a set of REST services, more information can be found here: link:../../rest/rest-btm.html[BTM REST services]

CAUTION: The standalone server does not currently support a clustered configuration.

The instructions for installing the server can be found here: link:serverinstall.html[Server Installation]

=== The User Interface

Once the server has been installed, and started, you will be able to start up the user interface by pointing a browser to: http://localhost:<port>/hawkular/btm-ui

_Where 'port' is the port used by the server (e.g. 8180 if port offset of 100 has been used)._

The default username and password when first starting the server is *_jdoe_* and *_password_*.

==== Kibana analytics dashboard

The UI currently only provides access to the Kibana analytics dashboard, showing the response time information derived from the executing business transaction instances.

Some tips on using Kibana:

* The 'filters' green tab at the top of the page can be expanded to show the current filters that have been applied. Whenever you select a time region (from the top chart), or select a magnifying glass or no entry icon, this will cause the information being viewed to be further constrained by adding an additional filter. When you wish to revert back to a previous level of information, simply remove (or disable) the particular filter box.

* In the lower table, showing the latest response time 'records', you can select the fields in the left hand column to get further statistics regarding the different values.

Further information on using Kibana can be found here: https://www.elastic.co/guide/en/kibana/3.0/index.html


== Business Transaction Configuration

Out of the box, BTM is configured with instrumentation rules for a selection of technologies, that can used to monitor generic information about business transaction instances executing over those technologies.

However, to make this information more useful in a business context, it is important to also be able to extract relevant details from the business messages, to aid future analysis. This section will explain how the additional "business transaction specific configuration" can be provided.

NOTE: In future releases, UI tools will be provided to help capture this configuration information. However, until then, the details will need to be defined in JSON files. These files are located within the BTM server, under the *_standalone/data/btmconfig_* folder.

[source,json]
.Example business transaction configuration for an Order Management example included within the RTGov project
----
{
  "businessTransactions": {
    "rtgov_samples_ordermgmt": {  // <1>
      "description": "Order Management example from RTGov",
      "filter": {
        "inclusions": [  // <2>
          "^/demo-orders/OrderService$"
        ]
      },
      "processors": [{  // <3>
        "nodeType": "Consumer",  // <4>
        "direction": "In",  // <5>
        "uriFilter": "^/demo-orders/OrderService$",  // <6>
        "actions": [{  // <7>
          "name": "all",
          "type": "{urn:switchyard-quickstart-demo:orders:1.0}submitOrder",
          "actionType": "AddContent",
          "expression": "XMLHelper.serialize(XMLHelper.selectNode(\"*[local-name() = 'Envelope']/*[local-name() = 'Body']/*[local-name() = 'submitOrder']\", values[0]))"
        },{
          "actionType": "AddCorrelationId",
          "scope": "Global",
          "expression": "XMLHelper.evaluate(\"*[local-name() = 'Envelope']/*[local-name() = 'Body']/*[local-name() = 'submitOrder']/order/orderId/text()\", values[0])"
        },{
          "name": "customer",
          "actionType": "SetProperty",
          "expression": "XMLHelper.evaluate(\"*[local-name() = 'Envelope']/*[local-name() = 'Body']/*[local-name() = 'submitOrder']/order/customer/text()\", values[0])"
        },{
          "name": "item",
          "actionType": "SetProperty",
          "expression": "XMLHelper.evaluate(\"*[local-name() = 'Envelope']/*[local-name() = 'Body']/*[local-name() = 'submitOrder']/order/itemId/text()\", values[0])"
        }]
      },{
        "nodeType": "Consumer",
        "direction": "Out",
        "uriFilter": "^/demo-orders/OrderService$",
        "actions": [{
          "name": "all",
          "type": "{urn:switchyard-quickstart-demo:orders:1.0}submitOrderResponse",
          "actionType": "AddContent",
          "expression": "XMLHelper.serialize(XMLHelper.selectNode(\"*[local-name() = 'Envelope']/*[local-name() = 'Body']/*[local-name() = 'submitOrderResponse']\", values[0]))"
        }]
      },{
        "nodeType": "Consumer",
        "direction": "Out",
        "uriFilter": "^/demo-orders/OrderService$",
        "predicate": "XMLHelper.evaluate(\"*[local-name() = 'Envelope']/*[local-name() = 'Body']/*[local-name() = 'Fault']\", values[0]) != null",  // <8>
        "actions": [{
          "actionType": "SetFault",
          "expression": "XMLHelper.evaluate(\"*[local-name() = 'Envelope']/*[local-name() = 'Body']/*[local-name() = 'Fault']/faultcode/text()\", values[0])"
        },{
          "actionType": "SetFaultDescription",
          "expression": "XMLHelper.evaluate(\"*[local-name() = 'Envelope']/*[local-name() = 'Body']/*[local-name() = 'Fault']/faultstring/text()\", values[0])"
        }]
      }]
    }
  }
}
----
<1> Each business transaction configuration must be given an unique name
<2> Inclusion filters define a regex expression used to match a URI in the captured information. If an inclusion filter matches, then the associated business transaction name will be added to the data reported to the server
<3> A list of information processors. Each entry in the list will define the criteria for matching against nodes in the business transaction fragment
<4> The 'nodeType' can identify one of the support node types, e.g. Consumer, Producer or Component
<5> The 'direction' field determines whether the *In* (i.e. request) or *Out* (i.e. response) direction should be processed
<6> The regex expression used to match against an URI of interest
<7> A list of actions to be performed by the processor, if the matching criteria are satisfied. Each action can have an optional predicate expression to determine if it should be applied. The list of supported action types, and their relevant fields, are described below.
<8> An optional predicate expression can be defined at the processor level, to guard against applying the actions it contains.

.Actions
|===
|Action Type |Description

|AddContent |Include content in the business transaction fragment node. Fields are '*_name_*' to distinguish content if multiple entries will be defined, '*_type_*' to classify the content type, and '*_expression_*' an MVEL expression to translate/extract the relevant content

|AddCorrelationId |Define correlation identifier used to correlate the current fragment with other fragments based on business context. The '*_scope_*' field can have values Global, Local (only relevant in the current service/app) or Interaction (scoped to the single interaction, i.e. shared between the communicating endpoints). The '*_expression_*' field is an MVEL expression used to extract the id.

|SetDetail |Extract a node specific value. The '*_name_*' field represents the name associated with the detail, and '*_expression_*' the MVEL expression used to extract the value

|SetFault |Define a fault value. The '*_expression_*' field is the MVEL expression used to extract the fault name

|SetFaultDescription |Define a fault description value. The '*_expression_*' field is the MVEL expression used to extract the fault description

|SetProperty |Extract a named business property. The '*_name_*' field names the business property, and '*_expression_*' defines the MVEL expression used to extract the value

|===


=== MVEL Expression Variables

The MVEL expressions are supplied the following variables:

|===
|Variable |Description

|btxn |The business transaction instance, of type _org.hawkular.btm.api.model.btxn.BusinessTransaction_.

|node |The current business transaction instance node being processed, type is derived from _org.hawkular.btm.api.model.btxn.Node_, current concrete types are _Consumer_, _Producer_ and _Component_ (within the same package).

|headers |A map of named header values.

|values |An array of values.

|===


=== Action Helper Classes

Some helper classes are provided for use within the action expressions.

.XMLHelper class
|===
|Method Signature |Description

|String evaluate(String xpath, Object node) |This method applies an XPath expression to the XML document/fragment supplied in the following formats:  _String_, _javax.xml.transform.dom.DOMSource_ and _org.w3c.dom.Node_.

|Node selectNode(String xpath, Object node) |This method applies an XPath expression to the XML document/fragment supplied in the following formats:  _String_, _javax.xml.transform.dom.DOMSource_ and _org.w3c.dom.Node_, to select a Node.

|String serialize(Object node) |This method attempts to serialize the supplied node as a textual representation of an XML document. The supported input formats are: _String_, _javax.xml.transform.dom.DOMSource_ and _org.w3c.dom.Node_.

|Node deserialize(Object node) |This method attempts to deserialize the supplied representation of an XML document. The supported input formats are: _String_, _javax.xml.transform.dom.DOMSource_ and _org.w3c.dom.Node_.

|===


== Properties

The system wide properties are now defined within a single *_btm.json_* file that is included within the _standalone/data/btmconfig_ folder of the BTM server.

The current properties that can be configured here are:

.BTM Properties
|===
|Property Name | Default | Description

|hawkular-btm.collector.onlynamed | false | Determine whether only business transaction fragments associated with a business transaction name should be reported.

|===



== Useful Links

. link:serverinstall.html[Server Installation]

. link:clientconfig.html[Client Configuration]

. link:btmrtgov.html[BTM/RTGov Integration]

