= Standalone Server Installation Guide
Gary Brown
2015-06-30
:description: Hawkular Business Transaction Management
:icons: font
:jbake-type: page
:jbake-status: published

This guide will help you to install a standalone Business Transaction Management server.

== Prerequisites

=== Java 8

You need a Java Virtual Machine compatible with Java 8.

== Obtaining the distribution

Check out the https://github.com/hawkular/hawkular-btm/releases[Hawkular BTM releases] page and download the latest
version of the distribution zip file: `hawkular-btm-dist-X.Y.Z.zip`

Unpack the zip file.

== Starting the BTM Server

The distribution contains some environment scripts for configuring the client-side collection mechanism. These scripts by default will report the information to _localhost_ and _port 8180_ (to avoid conflict with other web apps that may be using the default _8080 port_).

Therefore when starting the BTM server we will need to specify a port offset.

The BTM server uses Hawkular Accounts, to provide authorization and authentication. When the BTM server is started first time, it will be necessary to create a default configuration for use by Hawkular Accounts - part of which is a default user *'jdoe'* with password *'password'*.

Therefore the command to start the server first time, from the root folder of the distribution, will be:

```
bin/standalone.sh -Dkeycloak.import=standalone/configuration/hawkular-realm.json -Djboss.socket.binding.port-offset=100
```

Subsequent server starts would then only need to use:

```
bin/standalone.sh -Djboss.socket.binding.port-offset=100
```

See link:../../rest/rest-btm.html[Business Transaction Management REST API] for information on available APIs.

