= Standalone Server Installation Guide
Gary Brown
2015-06-30
:description: Hawkular Business Transaction Management
:icons: font
:jbake-type: page
:jbake-status: published
:toc: macro
:toc-title:

toc::[]

== Prerequisites

=== Java 8

You need a Java Virtual Machine compatible with Java 8.

== Obtaining the distribution

Check out the https://github.com/hawkular/hawkular-btm/releases[Hawkular BTM releases] page and download the latest
version of the distribution zip file: `hawkular-btm-dist-X.Y.Z.zip`

Unpack the zip file.

== Starting the Server

The distribution contains some environment scripts for configuring the client-side collection mechanism. These scripts by default will report the information to _localhost_ and _port 8180_ (to avoid conflict with other web apps that may be using the default _8080 port_).

Therefore when starting the Hawkular BTM server we will need to specify a port offset. The command to start the server, from the root folder of the distribution, will be:

[source,shell]
----
bin/standalone.sh -Djboss.socket.binding.port-offset=100 -Dkeycloak.server.url=http://localhost:8180/auth
----

NOTE: If a port offset is used, then it is also necessary to tell _keycloak_ where to find the
authorisation/authentication server. In the above example the base port is 8080 with an offset of 100,
and therefore the KC port is now 8080+100=8180.

When the server is initially started, it is not configured with any users. The BTM UI login page includes a link for registering a user. However, a default user profile is included within the distribution that includes a single user *_jdoe_* with password *_password_*. To import this default profile, the first time the server is started it should include the following _-Dkeycloak.import_ parameter:

[source,shell]
----
bin/standalone.sh -Djboss.socket.binding.port-offset=100 -Dkeycloak.server.url=http://localhost:8180/auth -Dkeycloak.import=standalone/configuration/hawkular-realm-for-dev.json
----



See link:../../rest/rest-btm.html[Business Transaction Management REST API] for information on available APIs.

