= Hawkular-Metrics 0.3.1 release
Stefan Negrea
2015-04-07
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, metrics, release

Hello Everybody,

I am happy to announce a big milestone for the Hawkular Metrics project. We are releasing today for the
first time from the repository hosted by the Hawkular organization.

Major changes:

UI::
  The core UI has been migrated to Hawkular UI related projects (hawkular-ui-components, hawkular, and
  hawkular-ui-services). The explorer project is still available for testing purposes.
REST::
. Consistent error reporting and status codes usage across endpoints
. Added Availability statistics (https://issues.jboss.org/browse/HWKMETRICS-35[HWKMETRICS-35]):
    * Total downtime duration
    * Last downtime
    * Percentage of uptime
    * Number of downtimes
. New Numeric Metric statistics (https://issues.jboss.org/browse/HWKMETRICS-34[HWKMETRICS-34]):
    * Average
    * Median
    * 95th Percentile
. The REST implementation has been decoupled from the actual core logic, which paves the way for alternate REST
implementations
Core::
* Large refactoring of the core classes and packages, the domain related logic has been pushed to the core layer
* The Memory storage engine has been dropped from the project. Cassandra (embedded or standalone) is the exclusive
storage engine.
InfluxDB Integration::
  Influx Java client supports sending and reading data (it was not possible before because of the endoint URI
differences) to/from Hawkular Metrics. Other clients are not tested but should work as well.
PTrans::
* Configurable list of listeners (previously all collectd, ganglia, ... etc listeners were started)
* Bug fix: send data to Metrics server if the buffer is full or no data was received recently (previously data could
sit in the buffer and wait for the buffer to be full before being sent)


Github Release:
https://github.com/hawkular/hawkular-metrics/releases/tag/0.3.1

JBoss Nexus Maven artifacts:
http://origin-repository.jboss.org/nexus/content/repositories/public/org/hawkular/metrics/


A big "Thank you" goes to John Sanda, Thomas Segismont, Mike Thompson, and Heiko Rupp for their project contributions. Special mentions go to Jeeva Kandasamy, Jirka Kremser, and Michael Burman for their project help.

I am happy to announce that Matt Wringe joined the Hawkular Metrics team with a focus on containers and project integrations. We are looking forward to his contributions.

Any discussion, suggestions or contributions are more than welcomed; so feel free to comment on this post or join
irc://irc.freenode.net/#hawkular[#Hawkular on freenode].

