= Monitoring Business Transactions in JBoss Ticket Monster App
Gary Brown
2015-11-10
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, btm, release


I am happy to announce release 0.5.0.Final of the Hawkular Business Transaction Management project.

The main focus of this release has been the development of a UI for configuring business transactions. This has lead to the introduction of an iterative approach for defining business transactions, as shown in this https://vimeo.com/145283731[demo monitoring the JBoss Ticket Monster application].

This demo shows how quickly an application can be monitored, without making any changes to the application, allowing business metrics to be obtained. In this case, the performance id can be captured from all bookings, allowing a pie chart to be displayed showing the percentage of bookings for each performance.

Feel free to try out Hawkular BTM on your own applications and provide feedback on any issues you find, or feature requests that you feel will improve the software.


== Highlights of this release

* UI for displaying summary details for Business Transactions

* UI for configuring information about a Business Transaction

* Business Transaction level filtering. Enables transaction information to be 'ignored' (permanently), 'disabled' (temporarily), or 'all'. Other intermediate levels of granularity may be supported in the future, including potentially filtering on a per instance basis.

* Support for JSON expression evaluation using JSONPath

* Deriving 'completion time' from Business Transaction instances, and storing independent from response time, in Elasticsearch. Percentile information is derived for the completion time, for use in the business transaction summary display

* Added instrumentation rules for observe EJB invocations in JBoss EAP and Wildfly servers

* Added action for REST URI template processing to extract path and query parameters as business transaction properties

* Implemented refresh mechanism for retrieving updates to business transaction configurations within the collector (client), enabling iterative approach for defining the configuration


Download the release from https://github.com/hawkular/hawkular-btm/releases/tag/0.5.0.Final[here].

Documentation on how to use Hawkular BTM can be found http://www.hawkular.org/docs/components/btm/index.html[here].

The detailed release notes can be found https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12316120&version=12328438[here].

Feature requests and bugs should be reported in our project https://issues.jboss.org/browse/HWKBTM[jira].


