= Hawkular Services 0.0.2.Final
Juraci Paixão Kröhling
2016-06-14
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, release, hawkular-services

Hawkular Services is a new base line distribution including only the basic Hawkular components, such as Alerts, Inventory and Metrics.
The version https://repository.jboss.org/nexus/content/groups/public/org/hawkular/services/hawkular-services-dist/0.0.2.Final/hawkular-services-dist-0.0.2.Final.zip[0.0.2.Final] has just been released and is ready to be tested and integrated with other projects.

Notable differences between the main Hawkular distribution and Hawkular Services are:

* Hawkular Services does not ship with a User Interface. Interaction with the backend is exclusively done via REST.
* Authentication is accomplished via JAAS, configured directly via Wildfly. Please refer to the Wildfly documentation on how to accomplish scenarios like LDAP user database.
* Due to the changes in the authentication, Keycloak is not part of the distribution, although it can still be used via JAAS. Please refer to the Keycloak documentation on how to protect deployments.
* Due to the removal of Keycloak, multi tenancy is also simplified. The backend endpoints expect to receive a `Hawkular-Tenant`, so, multi tenancy is now handled on the consumer side.

For more information on the details of this new distribution as well as the background, see the blog post http://www.hawkular.org/blog/2016/04/28/new-packaging.html[New Hawkular packaging]. Note that
`hawkular-core-services` on that post is what we now know as `hawkular-services`.

Hawkular Services is released every week on Tuesdays.

To get started with Hawkular Services, https://repository.jboss.org/nexus/content/groups/public/org/hawkular/services/hawkular-services-dist/0.0.2.Final/hawkular-services-dist-0.0.2.Final.zip[download the latest release], unzip it, add a user and set the Agent to use the credentials for the user just added.
It can be accomplished with the following commands:

```
export HAWKULAR_HOME="/path/to/hawkular-services"
export HAWKULAR_USERNAME="jdoe"
export HAWKULAR_PASSWORD="password"

cd "${HAWKULAR_HOME}"
"${HAWKULAR_HOME}/bin/add-user.sh" \
  -a \
  -u "${HAWKULAR_USERNAME}" \
  -p "${HAWKULAR_PASSWORD}" \
  -g read-write,read-only
"${HAWKULAR_HOME}/bin/standalone.sh" -Dhawkular.rest.user="${HAWKULAR_USERNAME}" -Dhawkular.rest.password="${HAWKULAR_PASSWORD}"
```
