= Hawkular Metrics 0.6.0 - Release
Stefan Negrea
2015-08-29
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, metrics, release


I am happy to announce release 0.6.0 of Hawkular Metrics. The release is anchored by enhancements for counter metrics, updates to the container infrastructure, and overall performance and stability enhancements.

== Major Changes:

. **Querying**
  * Metrics can now be searched with regexp filtering capabilities on tags
  * Metrics queries now support logical AND for tags
. **Internal**
  * TenantId and type were moved to the MetricId instead of Metric class
  * Implicit tenants (not manaully created prior to sending first set of metric data) are now created on metrics insertion
. **Container**
  * Updated to the latest Heapster version (0.17)
  * The communication between the Hawkular Metrics and Cassandra containers have now been secured. This means that only Hawkular Metrics can communicate with its Cassandra containers.
. **Counters**
 * Per-minute rates can be retrieved via the /hawkular/metrics/counters/{id}/rate endpoint.
. **Task scheduling**
  * The scheduler API and schema has undergone several changes. It is now possible to group related tasks so that order of execution can be controlled when there are interdependencies. There is still ongoing work to support asynchronous job execution and to provide fault tolerance.
. **Ruby Client**
  * The project has now an official Ruby client, this joins the existing Go and Python clients.

== Hawkular Metrics Clients
One of Hawkular Metrics' objectives is to *be easy to integrate with*; providing language specific clients is an important component for fulfilling this objective. Here is the current list of official clients:

* Ruby: https://github.com/hawkular/hawkular-client-ruby
* Python: https://github.com/hawkular/hawkular-client-python
* Go: https://github.com/hawkular/hawkular-client-go

== Release links

* Github Release:
** https://github.com/hawkular/hawkular-metrics/releases/tag/0.6.0

* JBoss Nexus Maven artifacts:
** http://origin-repository.jboss.org/nexus/content/repositories/public/org/hawkular/metrics/

* Jira release tracker:
** https://issues.jboss.org/browse/HWKMETRICS/fixforversion/12327689/

== Thanks

A big "Thank  you" goes to John Sanda, Thomas Segismont, Mike Thompson, Matt Wringe, Michael Burman, Libor Zoubek, Jirka Kremser, and Heiko Rupp for their project  contributions.
