= Visualising Business Transaction Information using Hawkular BTM 0.3.0.Final with RTGov Integration
Gary Brown
2015-08-14
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, btm, demo, rtgov

The Hawkular Business Transaction Management (BTM) project has released version https://github.com/hawkular/hawkular-btm/releases/tag/0.3.0.Final[0.3.0.Final]. Some of the new features within this release:

* Extract correlation ids, properties/details and message content from business transaction instances. This enables the generic information captured by instrumenting the underlying technologies to be enhanced with business specific information that can be useful for later analysis and to help correlate different parts of an overall business transaction instance.

* BTM to RTGov gateway, to enable the business transaction instance data collected by BTM to be reported and visualised using RTGov (Runtime Governance) tooling.

* Fault path handling for switchyard services.


To demonstrate the use of Hawkular BTM, to extract business transaction specific data and report the information to RTGov, we have created a https://youtu.be/bxeRJAsAu_8[short screencast].

video::bxeRJAsAu_8[youtube]

Feel free to try out the latest release for yourself on your own applications. If you have any questions or comments, please contact us on link:/community/join.html[these channels].

If you have suggestions for features/enhancements, or find any bugs, then please log an issue in the https://issues.jboss.org/browse/HWKBTM[project jira].

