= Hawkular Alerting Tutorial: Lesson 06 - Events!
Jay Shaughnessy
2017-04-27
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, alerts

Announcing availability of Tutorial Lesson 06: Events!

This new lesson builds on the http://www.hawkular.org/blog/2017/03/14/hawkular-alerting-tutorial.html[previously announced tutorial].  It talks about events in Hawkular alerting, how they differ from alerts, and how to work with them. Check it out!

Hawkular Alerting is a pluggable, API-driven component for adding alerting to your application or tool.  It's one of the many http://hawkular.org[Hawkular] offerings for monitoring and management.  To help quick-start new users, and as a reference for current users, we've now released six tutorial lessons, with more to follow.  It's a great way to hit the ground running.

== For Git Users:

----
git clone https://github.com/hawkular/hawkular-alerts.git
cd hawkular-alerts/examples/tutorial
----

== For Others:

. Click this link to visit http://github.com/hawkular/hawkular-alerts[Hawkular Alerting on GitHub].
. Click _Clone or download_
. Click _Download ZIP_
+
[source,shell]
----
unzip hawkular-alerts-master.zip
cd hawkular-alerts/examples/tutorial
----

== For Everyone:

Start with the README.adoc. If you don't have an asciidoc extension in your browser you can read the rendered README https://github.com/hawkular/hawkular-alerts/blob/master/examples/tutorial/README.adoc[directly from GitHub].  From here just click links in the document to proceed.

Hawkular Alerting has several deployment options, it can be deployed standalone, or embedded in Hawkular Metrics, or as part of Hawkular Services.  The tutorial drives off of a docker container running alerting as part of Hawkular Metrics, generating alerts off of incoming metric data.  The first lesson will help you get set up.

Try it and let us know how it goes! If you have any questions or want to share your thoughts, join us on IRC at irc://irc.freenode.org/#hawkular[#hawkular on freenode].


