= Join Hawkular
Heiko Rupp
2015-02-16
:jbake-type: page
:jbake-status: published
:jbake-tags: community
:description: You are interested in Hawkular and would like to know where to start?

== Meet the developers

There are several ways to join the Hawkular community. The best option is always to talk to people and see what is
going on. There are several ways to reach the developers and other community members.

=== IRC

The Hawkular developers hang around on Internet Relay Chat (Irc) on irc://irc.freenode.net/#hawkular[irc://irc.freenode
.net/#hawkular] (check here of a http://webchat.freenode.net/?channels=hawkular[Web-client] if you can't use a irc
client on your machine).

=== Email

Developer discussions happen on the _hawkular-dev_ mailing list.
To join the discussions please visit the list manager
page at https://lists.jboss.org/mailman/listinfo/hawkular-dev and subscribe to the list.

Commit messages are sent to the _hawkular-commits_ mailing list. You can subscribe at
https://lists.jboss.org/mailman/listinfo/hawkular-commits


=== Twitter

Hawkular can be found as https://twitter.com/hawkular_org[@hawkular_org] on Twitter.


=== Issue tracker

Hawkular issues and feature requests and ideas are captured in the
https://issues.jboss.org/browse/HAWKULAR[Hawkular Jira] instance at JBoss.org. There are several individual trackers
for the various sub-project, but when in doubt, just
use the Hawkular one and we will re-assign the submissions.

== Contribute code

All code lives on GitHub under https://github.com/hawkular[https://github.com/hawkular]. To contribute, fork the
respective project(s), implement your changes and open a pull-request.


== Contribute documentation

Similar to code, the Hawkular website and documentation lives under
https://github.com/hawkular.github.io[https://github.com/hawkular.github.io]. And as with the code,
fork the repo, create your changes and open a pull-request.



