= Terms
Heiko Rupp
2015-03-30
:description: What do Kettle and so on mean?
:icons: font
:jbake-type: page
:jbake-status: published
:toc: macro
:toc-title:

Hawkular sometimes uses terms that are not everyone is familiar with. This page is an effort to clarify those.

Dampening:: This is a concept in Hawkular-Alerts that allows to "verify" an alerting condition. As an example,
sometimes one only wants to trigger an alert when the same conditions occurs at least three times in 5 minutes.
Feed:: A feed is a source of incoming data to pe processed by Hawkular. Usually a feed is something like an agent
that is collecting data, but it could also be an application sending data or a shell-script using the `curl` command
to submit the data.
Kettle:: The kettle is a runtime container of Hawkular that contains all the individual Hawkular components including
 Hawkular-Metrics, Hawkular-Alerts, the Pinger and many more
Pinger:: A component that "pings" footnote::[Not a ICMP-Ping, but a http call.] remote http servers and reports back
 the server status along with the time it took.
Trigger-Definition:: The Trigger definition consits of the rules when incoming conditions should trigger (fire) an
alert.

