= Monitoring Business Transactions in JBoss Ticket Monster App (Part 2)
Gary Brown
2015-11-30
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, btm, release


I am happy to announce release 0.6.0.Final of the Hawkular Business Transaction Management project.


The main focus for this release has been creating a UI to display statistical information about the configured business transactions. A demo can be seen https://vimeo.com/147347020[here].

== Highlights of this release

* Statistics page per business transaction configuration showing
** a histogram with min, avg, max details, and transaction/fault counts overlaid as a bar chart
** fault pie chart
** property pie chart with combobox to select the property of interest

* Selecting pie chart segment, for fault or property value, can add item to filter, focusing the information being displayed

* Validation capability added to the business transaction configuration UI page. If validation errors are detected in a business transaction configuration, it will be held in a staging area on the server, and is not published out to any active collector agents until fixed.

* URI candidate list compression - where many URIs are related to a template with path parameter, the parameter will be inferred, and only the template URI shown in the list

* Processing faults, captured in the collector, will now be associated with the business transaction fragment so that they can be handled with an understanding of the context in which they occurred

* Where available, the 'principal' will now be recorded against the business transaction (fragment). Servlet instrumentation rules have been updated to store this information on the business transaction, rather than node detail level.

* SQL prepared statement description now excludes any representation of binary data, to make the description more readable.

* JAVA_OPT parameters required to configure the collector (java) agent have now been simplified, moving the byteman properties into BTM specific agent

WARNING: There are some backward incompatible changes to the REST service APIs to hopefully make the APIs simpler and more consistent.


Download the release from https://github.com/hawkular/hawkular-btm/releases/tag/0.6.0.Final[here].

Documentation on how to use Hawkular BTM can be found http://www.hawkular.org/docs/components/btm/index.html[here].

The detailed release notes can be found https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12316120&version=12328755[here].

Feature requests and bugs should be reported in our project https://issues.jboss.org/browse/HWKBTM[jira].


