= Hawkular BTM component rename
Gary Brown
2016-06-01
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, btm, apm, distributed tracing, application performance, business transactions

When the Hawkular BTM component project was started in April 2015 the vision was to provide a Business Transaction Management solution - hence the name.

However, as demonstrated in the recent posts, the scope of the project has now expanded to include Application Performance Management, which as discussed in the APM Conceptual Framework on https://en.wikipedia.org/wiki/Application_performance_management[Wikipedia], subsumes the area of Business Transaction Management.

Therefore, to avoid confusion and prior to the project reaching a stable 1.0 version, we have decided to rename the component from Hawkular BTM to Hawkular APM.

This change will be implemented within the next couple of weeks, and will consist of renaming the github repository, the jira issue tracking system, the Java maven artifacts (and packages) and the REST endpoints. Therefore the next release will not be backward compatible with version 0.8.

If you have any questions regarding this change, please http://www.hawkular.org/community/index.html[contact us].

