= QR Code support for Android Client
Anuj Garg
2016-3-21
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, hawkular android client, QR

Hawkular Android Client now support QR code (contains combination of key, secret and optionally an expireAt attribute).
Tokens are great to be used as we can revoke it from the server without affecting the user credentials.

== Ways to log in

There are two ways to login into Hawkular Server with Android Client.

. With your credentials, client will generate a token for you and will save it for future use, until it is either expired or revoked.
. By using a already existing token. It can be done by simply opening QR code for corresponding token in the Web UI and scanning it with your android device.


== Watch the demo online

Visit the recording here:

video::kmI5kodxZmY[youtube,width=600,height=400]

== What’s next?

Triggers are needed to be handled remotely. So feature to create, enable and disable them remotely can be of great help. Activities in the next time will be around that goal.
