= Metrics Documentation
Thomas Segismont
2015-06-15
:icons: font
:jbake-type: page
:jbake-status: published

Hawkular Metrics is the metric data store part of the http://www.hawkular.org/[Hawkular] organization.
It is currently used as the metric storage engine for Hawkular but it can also be independently. The project relies on https://cassandra.apache.org/[Apache Cassandra] as a backend.


Three types of metrics are currently supported:

 * Availability: metric that represent availability: up or down
 * Counter: numeric value that always goes up; example: the total number of visitors of a web page
   ** Rates: rate of change can be retrieve for counter rates
 * Gauge: numeric value that can go up or down; example: the response time on an application
   ** Aggregate buckets (min/max/average on some intervals) can be obtained for gauges when individual datapoints are not needed

Tags are available for easy filtering and querying, along with retention times for automatic pruning of older data.


Please visit the following pages for more details:

* link:../../rest/rest-metrics.html[Metrics - REST API documentation]
* https://github.com/hawkular/hawkular-metrics[GitHub Repository]
* link:installation.html[Installation Guide]
* link:configuration.html[Configuration Guid]
* link:grafana_integration.html[Grafana integration]
