= Metrics Documentation
Thomas Segismont
2015-06-15
:icons: font
:jbake-type: page
:jbake-status: published
:toc: macro
:toc-title:

toc::[]

== Introduction
Hawkular Metrics is a metrics storage engine built on top of link:http://cassandra.apache.org[Cassandra] that offers
a rich, growing set of features that includes:

* Multi tenancy
* Multiple metric types
* Tagging
* Automatic data removal
* REST API
* Scalability
* Rich query support

== Identifiers
All identifiers are stored as variable length, UTF-8 encoded strings. This includes:

* Tenant ids
* Metric names (see <<Metric Ids>> section below for more details on metric names
* Tag keys (for both metric and data point tags)

[TIP]
At present there is no restriction on characters that can be used in identifiers. This may change in the future
though (See link:https://issues.jboss.org/browse/HWKMETRICS-208[HWKMETRICS-208] for details). For this reason it is
recommended to restrict the characters to letters, numbers, underscore, period, and forward slash.

[TIP]
If an identifier uses a character that is defined as special character in the HTTP spec, it must be encoded. Forward
slashes are no exception. If for example I have a tenant id of `com/acme`, then in HTTP requests it should be encoded
as `com%2Facme`.

== Multi Tenancy
Hawkular Metrics provides _virtual_ multi tenancy. All data is mapped to a tenant, but the data on disk is not
physically partitioned by tenant. From an API perspective though, everything is partitioned by tenant. All requests,
both reads and writes, must include a tenant id.

TIP: Tenants do not have to be explicitly created. They will be created when inserting data points.

=== Tenant Ids
A tenant has an id that uniquely identifies it. The id is a variable length, UTF-8 encoded string. Hawkular Metrics
does not perform any validation checks to prevent duplicate ids. This is in large part due to Cassandra's design. Among
other things, Cassandra is a key/value store. Inserting a row into Cassandra is similar to inserting an entry into a
map. If the key already exists in the map, it will simply be overwritten with the new value. This is exactly how
Cassandra behaves.

[IMPORTANT]
If a duplicate id is used, data will be silently overwritten. Users are responsible for ensuring that tenant ids are
unique.

== Metric Types
A metric represents a single time series or continuous stream of data points. A data point consists of a timestamp and
a value. The type of value will vary depending on the metric type. Three types of metrics are currently supported:

* Availability
* Gauge
* Counter

TIP: Metrics do not have to be explicitly created. They will be created when inserting data points.

TIP: A string metric type may be added in a future release. See
link:https://issues.jboss.org/browse/HWKMETRICS-384[HWKMETRICS-384] for details.

=== Availability
Represents the availability of a resource such as host machine (physical or virtual) or an application server. There
are only three supported availability types or values:

* up
* down
* unknown

Availability is stored as single, unsigned byte.

=== Gauge
Has a numeric value that can fluctuate, going up or down. Some examples of gauges include,

* Available heap space in the JVM
* Number of active HTTP sessions on a web server
* Disk space used by a database table
* Execution time for a REST API call

With each of these examples, values can increase or decrease. In some instances, like JVM heap space, there are
well-defined bounds for the possible values.

A gauge value is stored as a 64-bit floating point number.

=== Counter
Has a numeric value that monotonically increases or decreases. Some examples include:

* Total number of requests to a REST endpoint
* Total number of request timeouts for a Cassandra node
* Total number of request timeouts for a Cassandra cluster

These examples involve values that are always increase. Counters can also be decreasing.

A counter value is stored as a 64-bit signed long.

There are two types of counters commonly uses with time series databases (TSDB). One stores the current count or total with
each data point. The other stores the delta or increment with each data point. The former is more commonly used with
counters that can easily be maintained by the client. Tracking the total number of requests to a REST endpoint for a
specific server can be done easily by the client. Tracking the total number of requests for the endpoint across all
servers however is more challenging. This can be done more easily by storing the deltas and allowing the TSDB to
compute and maintain the total count.

Hawkular Metrics only supports the former in which each data point represents the total count; however, we can easily
simulate counters that store deltas. See the <<Incrementing Counters>> section for more details.

==== Rate
A rate is a derived metric whose values are computed from counter data points. Rate data points can retrieved for any
counter. They are stored as 64-bit floating point numbers.

== Metric Ids
Every metric has an id that uniquely identifies it. The id consists of three parts - the tenant id, the metric type,
and the metric name. The tenant id is a variable length, UTF-8 encoded string. The metric type is stored as a one byte
integer. The metric name is stored as a variable length, UTF-8 encoded string.

The parts that comprise the metric id provide namespacing. A metric name only has to be unique for the metric type and
the tenant. For example, suppose we have a tenant id of com.acme. The com.acme tenant could have a gauge named
http_request_time and also have a counter named http_request_time.

Just like with tenant ids, Hawkular Metrics does not perform any validation checks to ensure metric ids are unique.
It is also import to remember that the name portion of the id only needs to be unique for the metric type and tenant.

[IMPORTANT]
If a duplicate id is used, data will be silently overwritten. Users are responsible for ensuring that metric ids are
unique.

== Inserting Data
Inserting data is a synchronous operation with respect to the client. An HTTP response is not returned all data points
are inserted. On the server side, multiple inserts to the database are done in parallel to achieve higher throughput.

=== Failures
If there is an error inserting a data point, the operation is aborted and any data in the request not yet written into
the database will be ignored. When there is an error, there is no reliable way to determine the remaining data
points that still need to be persisted. This is due to the fact that writes to the database are asynchronous and are
done in parallel. This means data points will not necessarily be written in the order received.

[TIP]
Unless stated otherwise, it can be assumed that writes in Hawkular Metrics are idempotent as is the case with writing
data points. If there is an error writing data points, the client can simply retry the request.

=== Examples
There are several operations available for insert data points.

==== Gauge Data
[source,shell]
.Insert data points for a single gauge
----
curl -X POST http://server/hawkular/metrics/gauges/request_size/raw -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
[
  {"timestamp:" 1460413065369, "value": 3.14},
  {"timestamp:" 1460413025569, "value": 4.57},
  {"timestamp:" 1460111065369, "value": 5.056}
]
----

The gauge name is `request_size` and the endpoint is `/hawkular/metrics/gauges/$metric/raw`.
The value of the `timestamp` property should be a unix timestamp. +
 +

[source,shell]
.Insert data points for multiple gauges
----
curl -X POST http://server/hawkular/metrics/gauges/raw -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
[
  {
    "id": "free_memory",
    "data": [
      {"timestamp": 1460111065369, "value": 2048},
      {"timestamp": 1460151065369, "value": 2012}
    ]
  },
  {
    "id": "used_memory",
    "data": [
      {"timestamp": 1460111065369, "value": 2048},
      {"timestamp": 1460151065369, "value": 2075}
    ]
  }
]
----

The request body is a bit more complex. Each array element is an object that has `id` and `data` properties. `data`
contains an array of data points.

==== Counter Data
[source,shell]
.Insert data points for a single counter
----
curl -X POST http://server/hawkular/metrics/counters/total_requests/raw -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
[
  {"timestamp:" 1460413065369, "value": 69},
  {"timestamp:" 1460413025569, "value": 65},
  {"timestamp:" 1460111065369, "value": 51}
]
----


[source,shell]
.Insert data points for multiple counters
----
curl -X POST http://server/hawkular/metrics/counters/raw -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
[
  {
    "id": "page_views",
    "data": [
      {"timestamp": 1460111065369, "value": 238},
      {"timestamp": 1460151065369, "value": 254}
    ]
  },
  {
    "id": "error_count",
    "data": [
      {"timestamp": 1460111065369, "value": 12},
      {"timestamp": 1460151065369, "value": 17}
    ]
  }
]
----

==== Availability Data
[source,shell]
.Insert data points for a single availability
----
curl -X POST http://server/hawkular/metrics/availability/server1/raw -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
[
  {"timestamp:" 1460413065369, "value": "down"},
  {"timestamp:" 1460413025569, "value": "down"},
  {"timestamp:" 1460111065369, "value": "up"}
]
----


[source,shell]
.Insert data points for multiple availabilities
----
curl -X POST http://server/hawkular/metrics/availability/raw -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
[
  {
    "id": "server1",
    "data": [
      {"timestamp": 1460111065369, "value": "up"},
      {"timestamp": 1460151065369, "value": "up"}
    ]
  },
  {
    "id": "server2",
    "data": [
      {"timestamp": 1460111065369, "value": "unknown"},
      {"timestamp": 1460151065369, "value": "up"}
    ]
  }
]
----

==== Mixed Data
[source,shell]
----
curl -X POST http://server/hawkular/metrics/metrics/data -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
{
  "gauges": [
    {
      "id": "free_memory",
      "data": [
        {"timestamp": 1460111065369, "value": 2048},
        {"timestamp": 1460151065369, "value": 2012}
      ]
    },
    {
      "id": "used_memory",
      "data": [
        {"timestamp": 1460111065369, "value": 2048},
        {"timestamp": 1460151065369, "value": 2075}
      ]
    }
  ],
  "counters": [
    {
      "id": "page_views",
      "data": [
        {"timestamp": 1460111065369, "value": 238},
        {"timestamp": 1460151065369, "value": 254}
      ]
    },
    {
      "id": "error_count",
      "data": [
        {"timestamp": 1460111065369, "value": 12},
        {"timestamp": 1460151065369, "value": 17}
      ]
    }
  ],
  "availability": [
    {
      "id": "server1",
      "data": [
        {"timestamp": 1460111065369, "value": "up"},
        {"timestamp": 1460151065369, "value": "up"}
      ]
    },
    {
      "id": "server2",
      "data": [
        {"timestamp": 1460111065369, "value": "unknown"},
        {"timestamp": 1460151065369, "value": "up"}
      ]
    }
  ]
}
----

== Data Retention and Removal
Metric data is automatically deleted from the system after an amount of time that is determined by data retention
settings. Data retention can be specified at various levels and is specified in days. There is a system-wide default of
seven days. This setting will apply to all metrics in the system if no other settings are specified. The system-wide
setting can be overridden at start up by either setting the `hawkular.metrics.default-ttl` system property or by
setting the `DEFAULT_TTL` environment variable.

Data retention can also be set per tenant. To do this, you need to explicitly create the tenant as in the following
example.

[source,shell]
----
curl -X POST http://server/hawkular/metrics/tenants -d @request.json \
-H "Content-Type: application/json"
----

[source,javascript]
.request.json
----
{
  "id": "com.acme",
  "retentions": {
    "gauge": 10,
    "counter": 5,
    "availability": 8
  }
}
----

This example uses the curl shell command. The request body is put in a file to improve readability. The `retentions`
map consists of names of one or more metric types. The value of each is an integer which represents the data retention
for that metric type in days.

You can also set data retention at the individual metric level. This would override any tenant data retention as well
as the system-wide default. Here is an example.

[source,shell]
----
curl -X POST http://server/hawkular/metrics/metrics -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
{
  "id": "request_size",
  "dataRetention": 10
}
----

This request creates a gauge named `request_size` with a data retention of 10 days.

WARNING: Hawkular Metrics currently lacks APIs for changing data retention. See
https://issues.jboss.org/browse/HWKMETRICS-380[HWKMETRICS-380] for details.

*TODO*
Add section on how Cassandra handles deletes.

== Creating Tenants and Metrics
*TODO*

== Tagging
Tags in Hawkular Metrics are key/value pairs. Tags can be applied to a metric to provide meta data for the time series
as a whole. Tags can also be applied to individual data points. Tags can be used to perform filtering in queries.

=== Creating Metric Tags
[source,shell]
----
curl -X POST http://server/hawkular/metrics/gauges -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
{
  "id": "request_size",
  "tags": {
    "datacenter": "dc1",
    "env": "stage"
    "units": "bytes"
  }
}
----

There are similar endpoints for other metric types.

=== Updating Metric Tags
This endpoint is used to add or replace tags.

[source,shell]
----
curl -X PUT http://server/hawkular/metrics/gauges/request_size/tags -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
----
{
  "datacenter": "dc2",
  "hostname": "server1"
}
----

=== Deleting Metric Tags
[source,shell]
----
curl -X DELETE http://server/hawkular/metrics/gauges/request_size/tags -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
----
{
  "env": "stage",
  "status": "active"
}
----

[TIP]
Note that both the key and value have to have to be specified, but anything can be specified for the tag value.
In the future, this endpoint might be updated to only require the tag keys. See
https://issues.jboss.org/browse/HWKMETRICS-385[HWKMETRICS-385] for details.

=== Data Point Tags
Tags can be added to individual data points. They are a bit different than metric tags because they are immutable.
Tags cannot be added or updated after a data point is written. The following examples demonstrate how to add
tags to a data point.

[source,shell]
----
curl -X POST http://server/hawkular/metrics/gauges/raw -d @request.json \
-H "Content-Type: application/json" -H "Hawkular-Tenant: com.acme"
----

[source,javascript]
.request.json
----
[
  {
    "id": "request_size",
    "data": [
      {
        "timestamp": 1460111065369,
        "value": 2048
        "tags": {
          "clientId": "1234",
          "zone": "us-east-1"
        }
      },
      {
        "timestamp": 1460151065369,
        "value": 2012,
        "tags": {
          "clientId": "5678",
          "zone": "us-west-1"
        }
      }
    ]
  },
  {
    "id": "request_time",
    "data": [
      {
        "timestamp": 1460111065369,
        "value": 2048,
        "tags": {
          "clientId": "1234",
          "zone": "us-east-1"
        }
      },
      {
        "timestamp": 1460151065369,
        "value": 2075,
        "tags": {
          "clientId": "5678",
          "zone": "us-west-1"
        }
      }
    ]
  }
]
----

TIP: Data point tags can be supplied in requests to any of the endpoints that write data points.

=== Tag Filtering

Hawkular Metrics provides a mini tag filtering expression language that is available in several query APIs. It has a
number of features including:

* Search by tag key only, ignoring the value
** Only exact match searches are supported for tag keys
* Exact match search by key and value
* Search for any number of tag values, i.e., logical OR
* Regular expression support in tag value
* Negation in tag value
* Compound search filter

The remainder of this section provides several examples that illustrate the aforementioned features. Examples of how
tag filtering is supported in various APIs can be found in <<Querying>>.

[grid="all"]
|===
|Expression |Example |Description
|:* |zone:* |Search for tag named `zone` having any value.
|tag_name:value |zone:us-east-1 |Search for tag named `zone` having value `us-east-1`.
|tag_name:value1\|value2 |zone:us-east-1\|us-west-1 |Search for tag named `zone` having a value of either `us-east-1`
or `us-west-1`.
|tag_name:!value |zone:!us-east-1 |Search for tag named `zone` with any value except `us-east-1`.
|tag_name:regex |hostname:.*01 |Search for tag named `hostname` with a value that ends with `01`.
|tag_name:value,tag_name:value |zone:us-east-1,hostname:dbserver01 | Search for tag named `zone` with value `us-east-1`
and tag named `hostname` with value `dbserver01`.
|tag_name:value,tag_name:value1\|value2 |zone:us-east1,server:server01\|server02 |Search for tag named `zone`
with value `us-east-1` and tag named `server` having a value of either `server01` or `server01`.
|===

== Incrementing Counters
*TODO*

== Querying
*TODO*

== Security
*TODO*

== Links
Please visit the following pages for more details:

* link:../../rest/rest-metrics.html[Metrics - REST API documentation]
* https://github.com/hawkular/hawkular-metrics[GitHub Repository]
* link:installation.html[Installation Guide]
* link:configuration.html[Configuration Guide]
* link:grafana_integration.html[Grafana integration]
