= Distributed Tracing Workshop and OpenTracing Collaboration
Pavol Loffay
2017-03-15
:jbake-type: post
:jbake-status: published
:jbake-tags: blog

The Distributed tracing workshop is organized by the
https://groups.google.com/forum/#!forum/distributed-tracing[Distributed Tracing Workgroup]
and takes place approximately once a year. This time it was 18th-19th February in Berlin. It was a pleasure
to be there with people from various companies and share ideas and a common goal to improve distributed tracing.

== Summary

We discussed many things, and here are my main takeaways:

Key upcoming changes in OpenTracing:

* Formal project organization OTSC (keep reading).
* Clarification between logging, metrics and tracing. The discussion continues in https://github.com/opentracing/specification/pull/46[specification/pull/46].
* In-process context propagation. This feature will probably be the biggest change in the next OpenTracing
    version. It should solve inconvenient passing of parent context. Users would just start new span and if there
    is a parent available it will be automatically linked.

Trace context propagation:

* Currently there are no standard headers for passing trace context. Several tracing systems adopted
    OpenZipkin's https://github.com/openzipkin/b3-propagation[B3 Propagation]. Standardization of context header
    should help with concerns like CORS and linking together traces between different service providers.
    Proposed https://docs.google.com/document/d/1Mrw7hxVAkj7h98hvgRixDt1RrEJ5fsqqddPofIHRVvI/edit[document].

== Hawkular on OpenTracing Specification Council!

I am also happy to announce that the Hawkular project is part of the
https://github.com/opentracing/specification/blob/master/project_organization.md[OpenTracing Specification Council] (OTSC).
This more formal project organization structure will help with project growth and ensure that all major constituencies
are involved.

== Links
 * OpenTracing project organization: https://github.com/opentracing/specification/blob/master/project_organization.md
 * Trace context propagation proposal: https://docs.google.com/document/d/1Mrw7hxVAkj7h98hvgRixDt1RrEJ5fsqqddPofIHRVvI/edit?ts=58767913

A big "Thank  you" goes to Adrian Cole for organizing it and also to all attendees for sharing great ideas and knowledge
around distributed tracing. Do not forget to join the group and be informed about upcoming events!
