= Hawkular APM 0.9.0.Final Released
Gary Brown
2016-06-27
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, btm, apm, distributed tracing, application performance, business transactions

As mentioned in a blog post at the beginning of the month, the Hawkular BTM (Business Transaction Management) project has been renamed Hawkular APM (Application Performance Management), to reflect the wider scope of the project.

This is the first release under the new project name, and consequently there are a number of naming related changes (e.g. REST endpoints, Java package/class names, model, etc) that mean this release is *not* backward compatible with the previous release.

The details of the release can be found https://github.com/hawkular/hawkular-apm/releases/tag/0.9.0.Final[here].

As part of this release, we have also moved the documentation for the project to https://hawkular.gitbooks.io/hawkular-apm-user-guide/content/[gitbook].

If you have any questions regarding the change of name, or anything else related to the project, please http://www.hawkular.org/community/index.html[contact us].

